/**
 * @file binocan.c
 *
 * @brief This source file was generated by cantools version 41.0.0 Tue Nov 18 15:40:22 2025.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <string.h>

#include "binocan.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u64(
    uint64_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u64(
    uint64_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint32_t unpack_left_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) << shift);
}

static inline uint64_t unpack_left_shift_u64(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint64_t)((uint64_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

static inline uint32_t unpack_right_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) >> shift);
}

static inline uint64_t unpack_right_shift_u64(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint64_t)((uint64_t)(value & mask) >> shift);
}

int binocan_ext_uds_resp_pack(
    uint8_t *dst_p,
    const struct binocan_ext_uds_resp_t *src_p,
    size_t size)
{
    uint8_t ext_uds_resp;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    ext_uds_resp = (uint8_t)src_p->ext_uds_resp;
    dst_p[0] |= pack_left_shift_u8(ext_uds_resp, 0u, 0xffu);

    return (8);
}

int binocan_ext_uds_resp_unpack(
    struct binocan_ext_uds_resp_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint8_t ext_uds_resp;

    if (size < 8u) {
        return (-EINVAL);
    }

    ext_uds_resp = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->ext_uds_resp = (int8_t)ext_uds_resp;

    return (0);
}

int binocan_ext_uds_resp_init(struct binocan_ext_uds_resp_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct binocan_ext_uds_resp_t));

    return 0;
}

int8_t binocan_ext_uds_resp_ext_uds_resp_encode(double value)
{
    return (int8_t)(value);
}

double binocan_ext_uds_resp_ext_uds_resp_decode(int8_t value)
{
    return ((double)value);
}

bool binocan_ext_uds_resp_ext_uds_resp_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}

int binocan_ext_uds_req_pack(
    uint8_t *dst_p,
    const struct binocan_ext_uds_req_t *src_p,
    size_t size)
{
    uint8_t ext_uds_req;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    ext_uds_req = (uint8_t)src_p->ext_uds_req;
    dst_p[0] |= pack_left_shift_u8(ext_uds_req, 0u, 0xffu);

    return (8);
}

int binocan_ext_uds_req_unpack(
    struct binocan_ext_uds_req_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint8_t ext_uds_req;

    if (size < 8u) {
        return (-EINVAL);
    }

    ext_uds_req = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->ext_uds_req = (int8_t)ext_uds_req;

    return (0);
}

int binocan_ext_uds_req_init(struct binocan_ext_uds_req_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct binocan_ext_uds_req_t));

    return 0;
}

int8_t binocan_ext_uds_req_ext_uds_req_encode(double value)
{
    return (int8_t)(value);
}

double binocan_ext_uds_req_ext_uds_req_decode(int8_t value)
{
    return ((double)value);
}

bool binocan_ext_uds_req_ext_uds_req_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}

int binocan_rdb_uds_resp_pack(
    uint8_t *dst_p,
    const struct binocan_rdb_uds_resp_t *src_p,
    size_t size)
{
    uint8_t rdb_uds_resp;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    rdb_uds_resp = (uint8_t)src_p->rdb_uds_resp;
    dst_p[0] |= pack_left_shift_u8(rdb_uds_resp, 0u, 0xffu);

    return (8);
}

int binocan_rdb_uds_resp_unpack(
    struct binocan_rdb_uds_resp_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint8_t rdb_uds_resp;

    if (size < 8u) {
        return (-EINVAL);
    }

    rdb_uds_resp = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->rdb_uds_resp = (int8_t)rdb_uds_resp;

    return (0);
}

int binocan_rdb_uds_resp_init(struct binocan_rdb_uds_resp_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct binocan_rdb_uds_resp_t));

    return 0;
}

int8_t binocan_rdb_uds_resp_rdb_uds_resp_encode(double value)
{
    return (int8_t)(value);
}

double binocan_rdb_uds_resp_rdb_uds_resp_decode(int8_t value)
{
    return ((double)value);
}

bool binocan_rdb_uds_resp_rdb_uds_resp_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}

int binocan_rdb_uds_req_pack(
    uint8_t *dst_p,
    const struct binocan_rdb_uds_req_t *src_p,
    size_t size)
{
    uint8_t rdb_uds_req;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    rdb_uds_req = (uint8_t)src_p->rdb_uds_req;
    dst_p[0] |= pack_left_shift_u8(rdb_uds_req, 0u, 0xffu);

    return (8);
}

int binocan_rdb_uds_req_unpack(
    struct binocan_rdb_uds_req_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint8_t rdb_uds_req;

    if (size < 8u) {
        return (-EINVAL);
    }

    rdb_uds_req = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->rdb_uds_req = (int8_t)rdb_uds_req;

    return (0);
}

int binocan_rdb_uds_req_init(struct binocan_rdb_uds_req_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct binocan_rdb_uds_req_t));

    return 0;
}

int8_t binocan_rdb_uds_req_rdb_uds_req_encode(double value)
{
    return (int8_t)(value);
}

double binocan_rdb_uds_req_rdb_uds_req_decode(int8_t value)
{
    return ((double)value);
}

bool binocan_rdb_uds_req_rdb_uds_req_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}

int binocan_ldb_uds_resp_pack(
    uint8_t *dst_p,
    const struct binocan_ldb_uds_resp_t *src_p,
    size_t size)
{
    uint8_t ldb_uds_resp;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    ldb_uds_resp = (uint8_t)src_p->ldb_uds_resp;
    dst_p[0] |= pack_left_shift_u8(ldb_uds_resp, 0u, 0xffu);

    return (8);
}

int binocan_ldb_uds_resp_unpack(
    struct binocan_ldb_uds_resp_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint8_t ldb_uds_resp;

    if (size < 8u) {
        return (-EINVAL);
    }

    ldb_uds_resp = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->ldb_uds_resp = (int8_t)ldb_uds_resp;

    return (0);
}

int binocan_ldb_uds_resp_init(struct binocan_ldb_uds_resp_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct binocan_ldb_uds_resp_t));

    return 0;
}

int8_t binocan_ldb_uds_resp_ldb_uds_resp_encode(double value)
{
    return (int8_t)(value);
}

double binocan_ldb_uds_resp_ldb_uds_resp_decode(int8_t value)
{
    return ((double)value);
}

bool binocan_ldb_uds_resp_ldb_uds_resp_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}

int binocan_ldb_uds_req_pack(
    uint8_t *dst_p,
    const struct binocan_ldb_uds_req_t *src_p,
    size_t size)
{
    uint8_t ldb_uds_req;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    ldb_uds_req = (uint8_t)src_p->ldb_uds_req;
    dst_p[0] |= pack_left_shift_u8(ldb_uds_req, 0u, 0xffu);

    return (8);
}

int binocan_ldb_uds_req_unpack(
    struct binocan_ldb_uds_req_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint8_t ldb_uds_req;

    if (size < 8u) {
        return (-EINVAL);
    }

    ldb_uds_req = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->ldb_uds_req = (int8_t)ldb_uds_req;

    return (0);
}

int binocan_ldb_uds_req_init(struct binocan_ldb_uds_req_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct binocan_ldb_uds_req_t));

    return 0;
}

int8_t binocan_ldb_uds_req_ldb_uds_req_encode(double value)
{
    return (int8_t)(value);
}

double binocan_ldb_uds_req_ldb_uds_req_decode(int8_t value)
{
    return ((double)value);
}

bool binocan_ldb_uds_req_ldb_uds_req_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}

int binocan_itf_uds_resp_pack(
    uint8_t *dst_p,
    const struct binocan_itf_uds_resp_t *src_p,
    size_t size)
{
    uint8_t itf_uds_resp;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    itf_uds_resp = (uint8_t)src_p->itf_uds_resp;
    dst_p[0] |= pack_left_shift_u8(itf_uds_resp, 0u, 0xffu);

    return (8);
}

int binocan_itf_uds_resp_unpack(
    struct binocan_itf_uds_resp_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint8_t itf_uds_resp;

    if (size < 8u) {
        return (-EINVAL);
    }

    itf_uds_resp = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->itf_uds_resp = (int8_t)itf_uds_resp;

    return (0);
}

int binocan_itf_uds_resp_init(struct binocan_itf_uds_resp_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct binocan_itf_uds_resp_t));

    return 0;
}

int8_t binocan_itf_uds_resp_itf_uds_resp_encode(double value)
{
    return (int8_t)(value);
}

double binocan_itf_uds_resp_itf_uds_resp_decode(int8_t value)
{
    return ((double)value);
}

bool binocan_itf_uds_resp_itf_uds_resp_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}

int binocan_itf_uds_req_pack(
    uint8_t *dst_p,
    const struct binocan_itf_uds_req_t *src_p,
    size_t size)
{
    uint8_t itf_uds_req;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    itf_uds_req = (uint8_t)src_p->itf_uds_req;
    dst_p[0] |= pack_left_shift_u8(itf_uds_req, 0u, 0xffu);

    return (8);
}

int binocan_itf_uds_req_unpack(
    struct binocan_itf_uds_req_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint8_t itf_uds_req;

    if (size < 8u) {
        return (-EINVAL);
    }

    itf_uds_req = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->itf_uds_req = (int8_t)itf_uds_req;

    return (0);
}

int binocan_itf_uds_req_init(struct binocan_itf_uds_req_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct binocan_itf_uds_req_t));

    return 0;
}

int8_t binocan_itf_uds_req_itf_uds_req_encode(double value)
{
    return (int8_t)(value);
}

double binocan_itf_uds_req_itf_uds_req_decode(int8_t value)
{
    return ((double)value);
}

bool binocan_itf_uds_req_itf_uds_req_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}

int binocan_itf_board_version_pack(
    uint8_t *dst_p,
    const struct binocan_itf_board_version_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->itf_version_mux, 0u, 0x03u);

    switch (src_p->itf_version_mux) {

    case 0:
        dst_p[0] |= pack_left_shift_u8(src_p->itf_version_dirty, 2u, 0x04u);
        dst_p[1] |= pack_left_shift_u8(src_p->itf_version_major, 0u, 0xffu);
        dst_p[2] |= pack_left_shift_u8(src_p->itf_version_minor, 0u, 0xffu);
        dst_p[3] |= pack_left_shift_u8(src_p->itf_version_patch, 0u, 0xffu);
        break;

    case 1:
        dst_p[1] |= pack_left_shift_u64(src_p->itf_version_commit, 0u, 0xffu);
        dst_p[2] |= pack_right_shift_u64(src_p->itf_version_commit, 8u, 0xffu);
        dst_p[3] |= pack_right_shift_u64(src_p->itf_version_commit, 16u, 0xffu);
        dst_p[4] |= pack_right_shift_u64(src_p->itf_version_commit, 24u, 0xffu);
        dst_p[5] |= pack_right_shift_u64(src_p->itf_version_commit, 32u, 0xffu);
        dst_p[6] |= pack_right_shift_u64(src_p->itf_version_commit, 40u, 0xffu);
        dst_p[7] |= pack_right_shift_u64(src_p->itf_version_commit, 48u, 0xffu);
        break;

    default:
        break;
    }

    return (8);
}

int binocan_itf_board_version_unpack(
    struct binocan_itf_board_version_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->itf_version_mux = unpack_right_shift_u8(src_p[0], 0u, 0x03u);

    switch (dst_p->itf_version_mux) {

    case 0:
        dst_p->itf_version_dirty = unpack_right_shift_u8(src_p[0], 2u, 0x04u);
        dst_p->itf_version_major = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
        dst_p->itf_version_minor = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
        dst_p->itf_version_patch = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
        break;

    case 1:
        dst_p->itf_version_commit = unpack_right_shift_u64(src_p[1], 0u, 0xffu);
        dst_p->itf_version_commit |= unpack_left_shift_u64(src_p[2], 8u, 0xffu);
        dst_p->itf_version_commit |= unpack_left_shift_u64(src_p[3], 16u, 0xffu);
        dst_p->itf_version_commit |= unpack_left_shift_u64(src_p[4], 24u, 0xffu);
        dst_p->itf_version_commit |= unpack_left_shift_u64(src_p[5], 32u, 0xffu);
        dst_p->itf_version_commit |= unpack_left_shift_u64(src_p[6], 40u, 0xffu);
        dst_p->itf_version_commit |= unpack_left_shift_u64(src_p[7], 48u, 0xffu);
        break;

    default:
        break;
    }

    return (0);
}

int binocan_itf_board_version_init(struct binocan_itf_board_version_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct binocan_itf_board_version_t));

    return 0;
}

uint8_t binocan_itf_board_version_itf_version_mux_encode(double value)
{
    return (uint8_t)(value);
}

double binocan_itf_board_version_itf_version_mux_decode(uint8_t value)
{
    return ((double)value);
}

bool binocan_itf_board_version_itf_version_mux_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t binocan_itf_board_version_itf_version_dirty_encode(double value)
{
    return (uint8_t)(value);
}

double binocan_itf_board_version_itf_version_dirty_decode(uint8_t value)
{
    return ((double)value);
}

bool binocan_itf_board_version_itf_version_dirty_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t binocan_itf_board_version_itf_version_major_encode(double value)
{
    return (uint8_t)(value);
}

double binocan_itf_board_version_itf_version_major_decode(uint8_t value)
{
    return ((double)value);
}

bool binocan_itf_board_version_itf_version_major_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint64_t binocan_itf_board_version_itf_version_commit_encode(double value)
{
    return (uint64_t)(value);
}

double binocan_itf_board_version_itf_version_commit_decode(uint64_t value)
{
    return ((double)value);
}

bool binocan_itf_board_version_itf_version_commit_is_in_range(uint64_t value)
{
    return (value <= 72057594037927904ull);
}

uint8_t binocan_itf_board_version_itf_version_minor_encode(double value)
{
    return (uint8_t)(value);
}

double binocan_itf_board_version_itf_version_minor_decode(uint8_t value)
{
    return ((double)value);
}

bool binocan_itf_board_version_itf_version_minor_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t binocan_itf_board_version_itf_version_patch_encode(double value)
{
    return (uint8_t)(value);
}

double binocan_itf_board_version_itf_version_patch_decode(uint8_t value)
{
    return ((double)value);
}

bool binocan_itf_board_version_itf_version_patch_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int binocan_rdb_st_pack(
    uint8_t *dst_p,
    const struct binocan_rdb_st_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->rdb_sm_st, 0u, 0x0fu);

    return (8);
}

int binocan_rdb_st_unpack(
    struct binocan_rdb_st_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->rdb_sm_st = unpack_right_shift_u8(src_p[0], 0u, 0x0fu);

    return (0);
}

int binocan_rdb_st_init(struct binocan_rdb_st_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct binocan_rdb_st_t));

    return 0;
}

uint8_t binocan_rdb_st_rdb_sm_st_encode(double value)
{
    return (uint8_t)(value);
}

double binocan_rdb_st_rdb_sm_st_decode(uint8_t value)
{
    return ((double)value);
}

bool binocan_rdb_st_rdb_sm_st_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

int binocan_ldb_st_pack(
    uint8_t *dst_p,
    const struct binocan_ldb_st_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->ldb_sm_st, 0u, 0x0fu);

    return (8);
}

int binocan_ldb_st_unpack(
    struct binocan_ldb_st_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->ldb_sm_st = unpack_right_shift_u8(src_p[0], 0u, 0x0fu);

    return (0);
}

int binocan_ldb_st_init(struct binocan_ldb_st_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct binocan_ldb_st_t));

    return 0;
}

uint8_t binocan_ldb_st_ldb_sm_st_encode(double value)
{
    return (uint8_t)(value);
}

double binocan_ldb_st_ldb_sm_st_decode(uint8_t value)
{
    return ((double)value);
}

bool binocan_ldb_st_ldb_sm_st_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

int binocan_itf_board_st_pack(
    uint8_t *dst_p,
    const struct binocan_itf_board_st_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->itf_hi_r_sense_st, 1u, 0x02u);
    dst_p[0] |= pack_left_shift_u8(src_p->itf_expander_st, 2u, 0x04u);
    dst_p[0] |= pack_left_shift_u8(src_p->itf_adc_st, 3u, 0x08u);
    dst_p[0] |= pack_left_shift_u8(src_p->itf_5_v_aux_st, 4u, 0x10u);
    dst_p[0] |= pack_left_shift_u8(src_p->itf_5_v_st, 5u, 0x20u);
    dst_p[0] |= pack_left_shift_u8(src_p->itf_ld_check_alive_st, 6u, 0x40u);
    dst_p[0] |= pack_left_shift_u8(src_p->itf_rd_check_alive_st, 7u, 0x80u);
    dst_p[1] |= pack_left_shift_u8(src_p->itf_sm_st, 5u, 0xe0u);
    dst_p[2] |= pack_left_shift_u8(src_p->itf_mcu_temp, 1u, 0xfeu);

    return (8);
}

int binocan_itf_board_st_unpack(
    struct binocan_itf_board_st_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->itf_hi_r_sense_st = unpack_right_shift_u8(src_p[0], 1u, 0x02u);
    dst_p->itf_expander_st = unpack_right_shift_u8(src_p[0], 2u, 0x04u);
    dst_p->itf_adc_st = unpack_right_shift_u8(src_p[0], 3u, 0x08u);
    dst_p->itf_5_v_aux_st = unpack_right_shift_u8(src_p[0], 4u, 0x10u);
    dst_p->itf_5_v_st = unpack_right_shift_u8(src_p[0], 5u, 0x20u);
    dst_p->itf_ld_check_alive_st = unpack_right_shift_u8(src_p[0], 6u, 0x40u);
    dst_p->itf_rd_check_alive_st = unpack_right_shift_u8(src_p[0], 7u, 0x80u);
    dst_p->itf_sm_st = unpack_right_shift_u8(src_p[1], 5u, 0xe0u);
    dst_p->itf_mcu_temp = unpack_right_shift_u8(src_p[2], 1u, 0xfeu);

    return (0);
}

int binocan_itf_board_st_init(struct binocan_itf_board_st_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct binocan_itf_board_st_t));

    return 0;
}

uint8_t binocan_itf_board_st_itf_hi_r_sense_st_encode(double value)
{
    return (uint8_t)(value);
}

double binocan_itf_board_st_itf_hi_r_sense_st_decode(uint8_t value)
{
    return ((double)value);
}

bool binocan_itf_board_st_itf_hi_r_sense_st_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t binocan_itf_board_st_itf_expander_st_encode(double value)
{
    return (uint8_t)(value);
}

double binocan_itf_board_st_itf_expander_st_decode(uint8_t value)
{
    return ((double)value);
}

bool binocan_itf_board_st_itf_expander_st_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t binocan_itf_board_st_itf_adc_st_encode(double value)
{
    return (uint8_t)(value);
}

double binocan_itf_board_st_itf_adc_st_decode(uint8_t value)
{
    return ((double)value);
}

bool binocan_itf_board_st_itf_adc_st_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t binocan_itf_board_st_itf_5_v_aux_st_encode(double value)
{
    return (uint8_t)(value);
}

double binocan_itf_board_st_itf_5_v_aux_st_decode(uint8_t value)
{
    return ((double)value);
}

bool binocan_itf_board_st_itf_5_v_aux_st_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t binocan_itf_board_st_itf_5_v_st_encode(double value)
{
    return (uint8_t)(value);
}

double binocan_itf_board_st_itf_5_v_st_decode(uint8_t value)
{
    return ((double)value);
}

bool binocan_itf_board_st_itf_5_v_st_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t binocan_itf_board_st_itf_ld_check_alive_st_encode(double value)
{
    return (uint8_t)(value);
}

double binocan_itf_board_st_itf_ld_check_alive_st_decode(uint8_t value)
{
    return ((double)value);
}

bool binocan_itf_board_st_itf_ld_check_alive_st_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t binocan_itf_board_st_itf_rd_check_alive_st_encode(double value)
{
    return (uint8_t)(value);
}

double binocan_itf_board_st_itf_rd_check_alive_st_decode(uint8_t value)
{
    return ((double)value);
}

bool binocan_itf_board_st_itf_rd_check_alive_st_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t binocan_itf_board_st_itf_sm_st_encode(double value)
{
    return (uint8_t)(value);
}

double binocan_itf_board_st_itf_sm_st_decode(uint8_t value)
{
    return ((double)value);
}

bool binocan_itf_board_st_itf_sm_st_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

uint8_t binocan_itf_board_st_itf_mcu_temp_encode(double value)
{
    return (uint8_t)(value);
}

double binocan_itf_board_st_itf_mcu_temp_decode(uint8_t value)
{
    return ((double)value);
}

bool binocan_itf_board_st_itf_mcu_temp_is_in_range(uint8_t value)
{
    return (value <= 127u);
}

int binocan_itf_odometer_pack(
    uint8_t *dst_p,
    const struct binocan_itf_odometer_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u32(src_p->itf_odometer_km, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->itf_odometer_km, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->itf_odometer_km, 16u, 0x0fu);
    dst_p[2] |= pack_left_shift_u8(src_p->itf_odo_rem_m, 4u, 0xf0u);
    dst_p[3] |= pack_left_shift_u16(src_p->itf_trip_km, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->itf_trip_km, 8u, 0x0fu);
    dst_p[4] |= pack_left_shift_u8(src_p->itf_trip_rem_m, 4u, 0xf0u);

    return (8);
}

int binocan_itf_odometer_unpack(
    struct binocan_itf_odometer_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->itf_odometer_km = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    dst_p->itf_odometer_km |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    dst_p->itf_odometer_km |= unpack_left_shift_u32(src_p[2], 16u, 0x0fu);
    dst_p->itf_odo_rem_m = unpack_right_shift_u8(src_p[2], 4u, 0xf0u);
    dst_p->itf_trip_km = unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->itf_trip_km |= unpack_left_shift_u16(src_p[4], 8u, 0x0fu);
    dst_p->itf_trip_rem_m = unpack_right_shift_u8(src_p[4], 4u, 0xf0u);

    return (0);
}

int binocan_itf_odometer_init(struct binocan_itf_odometer_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct binocan_itf_odometer_t));

    return 0;
}

uint32_t binocan_itf_odometer_itf_odometer_km_encode(double value)
{
    return (uint32_t)(value);
}

double binocan_itf_odometer_itf_odometer_km_decode(uint32_t value)
{
    return ((double)value);
}

bool binocan_itf_odometer_itf_odometer_km_is_in_range(uint32_t value)
{
    return (value <= 1048575u);
}

uint8_t binocan_itf_odometer_itf_odo_rem_m_encode(double value)
{
    return (uint8_t)(value / 100.0);
}

double binocan_itf_odometer_itf_odo_rem_m_decode(uint8_t value)
{
    return ((double)value * 100.0);
}

bool binocan_itf_odometer_itf_odo_rem_m_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint16_t binocan_itf_odometer_itf_trip_km_encode(double value)
{
    return (uint16_t)(value);
}

double binocan_itf_odometer_itf_trip_km_decode(uint16_t value)
{
    return ((double)value);
}

bool binocan_itf_odometer_itf_trip_km_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

uint8_t binocan_itf_odometer_itf_trip_rem_m_encode(double value)
{
    return (uint8_t)(value / 100.0);
}

double binocan_itf_odometer_itf_trip_rem_m_decode(uint8_t value)
{
    return ((double)value * 100.0);
}

bool binocan_itf_odometer_itf_trip_rem_m_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

int binocan_ext_chargecooling_metrics_pack(
    uint8_t *dst_p,
    const struct binocan_ext_chargecooling_metrics_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->bitmask, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->ext_charge_coolant_temp_in, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->ext_charge_coolant_temp_out, 0u, 0xffu);

    return (8);
}

int binocan_ext_chargecooling_metrics_unpack(
    struct binocan_ext_chargecooling_metrics_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->bitmask = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->ext_charge_coolant_temp_in = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->ext_charge_coolant_temp_out = unpack_right_shift_u8(src_p[2], 0u, 0xffu);

    return (0);
}

int binocan_ext_chargecooling_metrics_init(struct binocan_ext_chargecooling_metrics_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct binocan_ext_chargecooling_metrics_t));

    return 0;
}

uint8_t binocan_ext_chargecooling_metrics_bitmask_encode(double value)
{
    return (uint8_t)(value);
}

double binocan_ext_chargecooling_metrics_bitmask_decode(uint8_t value)
{
    return ((double)value);
}

bool binocan_ext_chargecooling_metrics_bitmask_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t binocan_ext_chargecooling_metrics_ext_charge_coolant_temp_in_encode(double value)
{
    return (uint8_t)(value);
}

double binocan_ext_chargecooling_metrics_ext_charge_coolant_temp_in_decode(uint8_t value)
{
    return ((double)value);
}

bool binocan_ext_chargecooling_metrics_ext_charge_coolant_temp_in_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t binocan_ext_chargecooling_metrics_ext_charge_coolant_temp_out_encode(double value)
{
    return (uint8_t)(value);
}

double binocan_ext_chargecooling_metrics_ext_charge_coolant_temp_out_decode(uint8_t value)
{
    return ((double)value);
}

bool binocan_ext_chargecooling_metrics_ext_charge_coolant_temp_out_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int binocan_itf_active_hi_lo_pack(
    uint8_t *dst_p,
    const struct binocan_itf_active_hi_lo_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->itf_ignition_ah_st, 0u, 0x01u);
    dst_p[0] |= pack_left_shift_u8(src_p->itf_hi_beams_ah_tt, 1u, 0x02u);
    dst_p[0] |= pack_left_shift_u8(src_p->itf_alternator_al_tt, 2u, 0x04u);
    dst_p[0] |= pack_left_shift_u8(src_p->itf_brake_low_al_tt, 3u, 0x08u);
    dst_p[0] |= pack_left_shift_u8(src_p->itf_parking_brake_al_tt, 4u, 0x10u);
    dst_p[0] |= pack_left_shift_u8(src_p->ext_oil_pressure_al_tt, 5u, 0x20u);
    dst_p[0] |= pack_left_shift_u8(src_p->itf_airbag_al_tt, 6u, 0x40u);
    dst_p[0] |= pack_left_shift_u8(src_p->itf_cel_al_tt, 7u, 0x80u);
    dst_p[1] |= pack_left_shift_u8(src_p->itf_right_turn_ah_tt, 0u, 0x01u);
    dst_p[1] |= pack_left_shift_u8(src_p->itf_left_turn_ah_tt, 1u, 0x02u);
    dst_p[1] |= pack_left_shift_u8(src_p->itf_abs_al_tt, 2u, 0x04u);
    dst_p[1] |= pack_left_shift_u8(src_p->itf_door_al_tt, 3u, 0x08u);
    dst_p[1] |= pack_left_shift_u8(src_p->itf_coolant_low_al_tt, 4u, 0x10u);
    dst_p[1] |= pack_left_shift_u8(src_p->itf_button_al, 5u, 0x20u);
    dst_p[1] |= pack_left_shift_u8(src_p->itf_alarm_ah, 6u, 0x40u);
    dst_p[1] |= pack_left_shift_u8(src_p->itf_backlight_ah, 7u, 0x80u);
    dst_p[2] |= pack_left_shift_u8(src_p->ext_over_temperature_tt, 0u, 0x01u);
    dst_p[2] |= pack_left_shift_u8(src_p->itf_fuel_low_tt, 1u, 0x02u);

    return (8);
}

int binocan_itf_active_hi_lo_unpack(
    struct binocan_itf_active_hi_lo_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->itf_ignition_ah_st = unpack_right_shift_u8(src_p[0], 0u, 0x01u);
    dst_p->itf_hi_beams_ah_tt = unpack_right_shift_u8(src_p[0], 1u, 0x02u);
    dst_p->itf_alternator_al_tt = unpack_right_shift_u8(src_p[0], 2u, 0x04u);
    dst_p->itf_brake_low_al_tt = unpack_right_shift_u8(src_p[0], 3u, 0x08u);
    dst_p->itf_parking_brake_al_tt = unpack_right_shift_u8(src_p[0], 4u, 0x10u);
    dst_p->ext_oil_pressure_al_tt = unpack_right_shift_u8(src_p[0], 5u, 0x20u);
    dst_p->itf_airbag_al_tt = unpack_right_shift_u8(src_p[0], 6u, 0x40u);
    dst_p->itf_cel_al_tt = unpack_right_shift_u8(src_p[0], 7u, 0x80u);
    dst_p->itf_right_turn_ah_tt = unpack_right_shift_u8(src_p[1], 0u, 0x01u);
    dst_p->itf_left_turn_ah_tt = unpack_right_shift_u8(src_p[1], 1u, 0x02u);
    dst_p->itf_abs_al_tt = unpack_right_shift_u8(src_p[1], 2u, 0x04u);
    dst_p->itf_door_al_tt = unpack_right_shift_u8(src_p[1], 3u, 0x08u);
    dst_p->itf_coolant_low_al_tt = unpack_right_shift_u8(src_p[1], 4u, 0x10u);
    dst_p->itf_button_al = unpack_right_shift_u8(src_p[1], 5u, 0x20u);
    dst_p->itf_alarm_ah = unpack_right_shift_u8(src_p[1], 6u, 0x40u);
    dst_p->itf_backlight_ah = unpack_right_shift_u8(src_p[1], 7u, 0x80u);
    dst_p->ext_over_temperature_tt = unpack_right_shift_u8(src_p[2], 0u, 0x01u);
    dst_p->itf_fuel_low_tt = unpack_right_shift_u8(src_p[2], 1u, 0x02u);

    return (0);
}

int binocan_itf_active_hi_lo_init(struct binocan_itf_active_hi_lo_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct binocan_itf_active_hi_lo_t));

    return 0;
}

uint8_t binocan_itf_active_hi_lo_itf_ignition_ah_st_encode(double value)
{
    return (uint8_t)(value);
}

double binocan_itf_active_hi_lo_itf_ignition_ah_st_decode(uint8_t value)
{
    return ((double)value);
}

bool binocan_itf_active_hi_lo_itf_ignition_ah_st_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t binocan_itf_active_hi_lo_itf_hi_beams_ah_tt_encode(double value)
{
    return (uint8_t)(value);
}

double binocan_itf_active_hi_lo_itf_hi_beams_ah_tt_decode(uint8_t value)
{
    return ((double)value);
}

bool binocan_itf_active_hi_lo_itf_hi_beams_ah_tt_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t binocan_itf_active_hi_lo_itf_alternator_al_tt_encode(double value)
{
    return (uint8_t)(value);
}

double binocan_itf_active_hi_lo_itf_alternator_al_tt_decode(uint8_t value)
{
    return ((double)value);
}

bool binocan_itf_active_hi_lo_itf_alternator_al_tt_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t binocan_itf_active_hi_lo_itf_brake_low_al_tt_encode(double value)
{
    return (uint8_t)(value);
}

double binocan_itf_active_hi_lo_itf_brake_low_al_tt_decode(uint8_t value)
{
    return ((double)value);
}

bool binocan_itf_active_hi_lo_itf_brake_low_al_tt_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t binocan_itf_active_hi_lo_itf_parking_brake_al_tt_encode(double value)
{
    return (uint8_t)(value);
}

double binocan_itf_active_hi_lo_itf_parking_brake_al_tt_decode(uint8_t value)
{
    return ((double)value);
}

bool binocan_itf_active_hi_lo_itf_parking_brake_al_tt_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t binocan_itf_active_hi_lo_ext_oil_pressure_al_tt_encode(double value)
{
    return (uint8_t)(value);
}

double binocan_itf_active_hi_lo_ext_oil_pressure_al_tt_decode(uint8_t value)
{
    return ((double)value);
}

bool binocan_itf_active_hi_lo_ext_oil_pressure_al_tt_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t binocan_itf_active_hi_lo_itf_airbag_al_tt_encode(double value)
{
    return (uint8_t)(value);
}

double binocan_itf_active_hi_lo_itf_airbag_al_tt_decode(uint8_t value)
{
    return ((double)value);
}

bool binocan_itf_active_hi_lo_itf_airbag_al_tt_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t binocan_itf_active_hi_lo_itf_cel_al_tt_encode(double value)
{
    return (uint8_t)(value);
}

double binocan_itf_active_hi_lo_itf_cel_al_tt_decode(uint8_t value)
{
    return ((double)value);
}

bool binocan_itf_active_hi_lo_itf_cel_al_tt_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t binocan_itf_active_hi_lo_itf_right_turn_ah_tt_encode(double value)
{
    return (uint8_t)(value);
}

double binocan_itf_active_hi_lo_itf_right_turn_ah_tt_decode(uint8_t value)
{
    return ((double)value);
}

bool binocan_itf_active_hi_lo_itf_right_turn_ah_tt_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t binocan_itf_active_hi_lo_itf_left_turn_ah_tt_encode(double value)
{
    return (uint8_t)(value);
}

double binocan_itf_active_hi_lo_itf_left_turn_ah_tt_decode(uint8_t value)
{
    return ((double)value);
}

bool binocan_itf_active_hi_lo_itf_left_turn_ah_tt_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t binocan_itf_active_hi_lo_itf_abs_al_tt_encode(double value)
{
    return (uint8_t)(value);
}

double binocan_itf_active_hi_lo_itf_abs_al_tt_decode(uint8_t value)
{
    return ((double)value);
}

bool binocan_itf_active_hi_lo_itf_abs_al_tt_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t binocan_itf_active_hi_lo_itf_door_al_tt_encode(double value)
{
    return (uint8_t)(value);
}

double binocan_itf_active_hi_lo_itf_door_al_tt_decode(uint8_t value)
{
    return ((double)value);
}

bool binocan_itf_active_hi_lo_itf_door_al_tt_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t binocan_itf_active_hi_lo_itf_coolant_low_al_tt_encode(double value)
{
    return (uint8_t)(value);
}

double binocan_itf_active_hi_lo_itf_coolant_low_al_tt_decode(uint8_t value)
{
    return ((double)value);
}

bool binocan_itf_active_hi_lo_itf_coolant_low_al_tt_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t binocan_itf_active_hi_lo_itf_button_al_encode(double value)
{
    return (uint8_t)(value);
}

double binocan_itf_active_hi_lo_itf_button_al_decode(uint8_t value)
{
    return ((double)value);
}

bool binocan_itf_active_hi_lo_itf_button_al_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t binocan_itf_active_hi_lo_itf_alarm_ah_encode(double value)
{
    return (uint8_t)(value);
}

double binocan_itf_active_hi_lo_itf_alarm_ah_decode(uint8_t value)
{
    return ((double)value);
}

bool binocan_itf_active_hi_lo_itf_alarm_ah_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t binocan_itf_active_hi_lo_itf_backlight_ah_encode(double value)
{
    return (uint8_t)(value);
}

double binocan_itf_active_hi_lo_itf_backlight_ah_decode(uint8_t value)
{
    return ((double)value);
}

bool binocan_itf_active_hi_lo_itf_backlight_ah_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t binocan_itf_active_hi_lo_ext_over_temperature_tt_encode(double value)
{
    return (uint8_t)(value);
}

double binocan_itf_active_hi_lo_ext_over_temperature_tt_decode(uint8_t value)
{
    return ((double)value);
}

bool binocan_itf_active_hi_lo_ext_over_temperature_tt_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t binocan_itf_active_hi_lo_itf_fuel_low_tt_encode(double value)
{
    return (uint8_t)(value);
}

double binocan_itf_active_hi_lo_itf_fuel_low_tt_decode(uint8_t value)
{
    return ((double)value);
}

bool binocan_itf_active_hi_lo_itf_fuel_low_tt_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int binocan_ext_oil_metrics_pack(
    uint8_t *dst_p,
    const struct binocan_ext_oil_metrics_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->bitmask, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->ext_oil_pressure, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->ext_oil_temperature, 0u, 0xffu);

    return (8);
}

int binocan_ext_oil_metrics_unpack(
    struct binocan_ext_oil_metrics_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->bitmask = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->ext_oil_pressure = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->ext_oil_temperature = unpack_right_shift_u8(src_p[2], 0u, 0xffu);

    return (0);
}

int binocan_ext_oil_metrics_init(struct binocan_ext_oil_metrics_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct binocan_ext_oil_metrics_t));

    return 0;
}

uint8_t binocan_ext_oil_metrics_bitmask_encode(double value)
{
    return (uint8_t)(value);
}

double binocan_ext_oil_metrics_bitmask_decode(uint8_t value)
{
    return ((double)value);
}

bool binocan_ext_oil_metrics_bitmask_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t binocan_ext_oil_metrics_ext_oil_pressure_encode(double value)
{
    return (uint8_t)(value / 0.1);
}

double binocan_ext_oil_metrics_ext_oil_pressure_decode(uint8_t value)
{
    return ((double)value * 0.1);
}

bool binocan_ext_oil_metrics_ext_oil_pressure_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t binocan_ext_oil_metrics_ext_oil_temperature_encode(double value)
{
    return (uint8_t)(value);
}

double binocan_ext_oil_metrics_ext_oil_temperature_decode(uint8_t value)
{
    return ((double)value);
}

bool binocan_ext_oil_metrics_ext_oil_temperature_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int binocan_itf_slow_metrics_pack(
    uint8_t *dst_p,
    const struct binocan_itf_slow_metrics_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->itf_coolant_temp, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->itf_fuel_level_pc, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->itf_lv_voltage_v, 0u, 0xffu);

    return (8);
}

int binocan_itf_slow_metrics_unpack(
    struct binocan_itf_slow_metrics_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->itf_coolant_temp = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->itf_fuel_level_pc = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->itf_lv_voltage_v = unpack_right_shift_u8(src_p[2], 0u, 0xffu);

    return (0);
}

int binocan_itf_slow_metrics_init(struct binocan_itf_slow_metrics_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct binocan_itf_slow_metrics_t));

    return 0;
}

uint8_t binocan_itf_slow_metrics_itf_coolant_temp_encode(double value)
{
    return (uint8_t)((value - 70.0) / 0.4);
}

double binocan_itf_slow_metrics_itf_coolant_temp_decode(uint8_t value)
{
    return (((double)value * 0.4) + 70.0);
}

bool binocan_itf_slow_metrics_itf_coolant_temp_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t binocan_itf_slow_metrics_itf_fuel_level_pc_encode(double value)
{
    return (uint8_t)(value / 0.5);
}

double binocan_itf_slow_metrics_itf_fuel_level_pc_decode(uint8_t value)
{
    return ((double)value * 0.5);
}

bool binocan_itf_slow_metrics_itf_fuel_level_pc_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t binocan_itf_slow_metrics_itf_lv_voltage_v_encode(double value)
{
    return (uint8_t)(value / 0.1);
}

double binocan_itf_slow_metrics_itf_lv_voltage_v_decode(uint8_t value)
{
    return ((double)value * 0.1);
}

bool binocan_itf_slow_metrics_itf_lv_voltage_v_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int binocan_itf_fast_metrics_pack(
    uint8_t *dst_p,
    const struct binocan_itf_fast_metrics_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->itf_rpm, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->itf_rpm, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->itf_speed_kph, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->itf_speed_kph, 8u, 0xffu);

    return (8);
}

int binocan_itf_fast_metrics_unpack(
    struct binocan_itf_fast_metrics_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->itf_rpm = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->itf_rpm |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->itf_speed_kph = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->itf_speed_kph |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);

    return (0);
}

int binocan_itf_fast_metrics_init(struct binocan_itf_fast_metrics_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct binocan_itf_fast_metrics_t));

    return 0;
}

uint16_t binocan_itf_fast_metrics_itf_rpm_encode(double value)
{
    return (uint16_t)(value / 0.14);
}

double binocan_itf_fast_metrics_itf_rpm_decode(uint16_t value)
{
    return ((double)value * 0.14);
}

bool binocan_itf_fast_metrics_itf_rpm_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t binocan_itf_fast_metrics_itf_speed_kph_encode(double value)
{
    return (uint16_t)(value / 0.04);
}

double binocan_itf_fast_metrics_itf_speed_kph_decode(uint16_t value)
{
    return ((double)value * 0.04);
}

bool binocan_itf_fast_metrics_itf_speed_kph_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}
