/**
 * @file binocan.c
 *
 * @brief This source file was generated by cantools version 41.0.0 Sun Nov 16 19:49:32 2025.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <string.h>

#include "binocan.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u64(
    uint64_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u64(
    uint64_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint32_t unpack_left_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) << shift);
}

static inline uint64_t unpack_left_shift_u64(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint64_t)((uint64_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

static inline uint32_t unpack_right_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) >> shift);
}

static inline uint64_t unpack_right_shift_u64(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint64_t)((uint64_t)(value & mask) >> shift);
}

int binocan_rd_uds_resp_pack(
    uint8_t *dst_p,
    const struct binocan_rd_uds_resp_t *src_p,
    size_t size)
{
    (void)src_p;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    return (8);
}

int binocan_rd_uds_resp_unpack(
    struct binocan_rd_uds_resp_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    (void)dst_p;
    (void)src_p;

    if (size < 8u) {
        return (-EINVAL);
    }

    return (0);
}

int binocan_rd_uds_resp_init(struct binocan_rd_uds_resp_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct binocan_rd_uds_resp_t));

    return 0;
}

int binocan_rd_uds_req_pack(
    uint8_t *dst_p,
    const struct binocan_rd_uds_req_t *src_p,
    size_t size)
{
    (void)src_p;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    return (8);
}

int binocan_rd_uds_req_unpack(
    struct binocan_rd_uds_req_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    (void)dst_p;
    (void)src_p;

    if (size < 8u) {
        return (-EINVAL);
    }

    return (0);
}

int binocan_rd_uds_req_init(struct binocan_rd_uds_req_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct binocan_rd_uds_req_t));

    return 0;
}

int binocan_ld_uds_resp_pack(
    uint8_t *dst_p,
    const struct binocan_ld_uds_resp_t *src_p,
    size_t size)
{
    (void)src_p;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    return (8);
}

int binocan_ld_uds_resp_unpack(
    struct binocan_ld_uds_resp_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    (void)dst_p;
    (void)src_p;

    if (size < 8u) {
        return (-EINVAL);
    }

    return (0);
}

int binocan_ld_uds_resp_init(struct binocan_ld_uds_resp_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct binocan_ld_uds_resp_t));

    return 0;
}

int binocan_ld_uds_req_pack(
    uint8_t *dst_p,
    const struct binocan_ld_uds_req_t *src_p,
    size_t size)
{
    (void)src_p;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    return (8);
}

int binocan_ld_uds_req_unpack(
    struct binocan_ld_uds_req_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    (void)dst_p;
    (void)src_p;

    if (size < 8u) {
        return (-EINVAL);
    }

    return (0);
}

int binocan_ld_uds_req_init(struct binocan_ld_uds_req_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct binocan_ld_uds_req_t));

    return 0;
}

int binocan_itfc_uds_resp_pack(
    uint8_t *dst_p,
    const struct binocan_itfc_uds_resp_t *src_p,
    size_t size)
{
    (void)src_p;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    return (8);
}

int binocan_itfc_uds_resp_unpack(
    struct binocan_itfc_uds_resp_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    (void)dst_p;
    (void)src_p;

    if (size < 8u) {
        return (-EINVAL);
    }

    return (0);
}

int binocan_itfc_uds_resp_init(struct binocan_itfc_uds_resp_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct binocan_itfc_uds_resp_t));

    return 0;
}

int binocan_itfc_uds_req_pack(
    uint8_t *dst_p,
    const struct binocan_itfc_uds_req_t *src_p,
    size_t size)
{
    (void)src_p;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    return (8);
}

int binocan_itfc_uds_req_unpack(
    struct binocan_itfc_uds_req_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    (void)dst_p;
    (void)src_p;

    if (size < 8u) {
        return (-EINVAL);
    }

    return (0);
}

int binocan_itfc_uds_req_init(struct binocan_itfc_uds_req_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct binocan_itfc_uds_req_t));

    return 0;
}

int binocan_interface_board_version_pack(
    uint8_t *dst_p,
    const struct binocan_interface_board_version_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->itfc_version_mux, 0u, 0x03u);

    switch (src_p->itfc_version_mux) {

    case 0:
        dst_p[0] |= pack_left_shift_u8(src_p->itfc_version_dirty, 2u, 0x04u);
        dst_p[1] |= pack_left_shift_u8(src_p->itfc_version_major, 0u, 0xffu);
        dst_p[2] |= pack_left_shift_u8(src_p->itfc_version_minor, 0u, 0xffu);
        dst_p[3] |= pack_left_shift_u8(src_p->itfc_version_patch, 0u, 0xffu);
        break;

    case 1:
        dst_p[1] |= pack_left_shift_u64(src_p->itfc_version_commit, 0u, 0xffu);
        dst_p[2] |= pack_right_shift_u64(src_p->itfc_version_commit, 8u, 0xffu);
        dst_p[3] |= pack_right_shift_u64(src_p->itfc_version_commit, 16u, 0xffu);
        dst_p[4] |= pack_right_shift_u64(src_p->itfc_version_commit, 24u, 0xffu);
        dst_p[5] |= pack_right_shift_u64(src_p->itfc_version_commit, 32u, 0xffu);
        dst_p[6] |= pack_right_shift_u64(src_p->itfc_version_commit, 40u, 0xffu);
        dst_p[7] |= pack_right_shift_u64(src_p->itfc_version_commit, 48u, 0xffu);
        break;

    default:
        break;
    }

    return (8);
}

int binocan_interface_board_version_unpack(
    struct binocan_interface_board_version_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->itfc_version_mux = unpack_right_shift_u8(src_p[0], 0u, 0x03u);

    switch (dst_p->itfc_version_mux) {

    case 0:
        dst_p->itfc_version_dirty = unpack_right_shift_u8(src_p[0], 2u, 0x04u);
        dst_p->itfc_version_major = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
        dst_p->itfc_version_minor = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
        dst_p->itfc_version_patch = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
        break;

    case 1:
        dst_p->itfc_version_commit = unpack_right_shift_u64(src_p[1], 0u, 0xffu);
        dst_p->itfc_version_commit |= unpack_left_shift_u64(src_p[2], 8u, 0xffu);
        dst_p->itfc_version_commit |= unpack_left_shift_u64(src_p[3], 16u, 0xffu);
        dst_p->itfc_version_commit |= unpack_left_shift_u64(src_p[4], 24u, 0xffu);
        dst_p->itfc_version_commit |= unpack_left_shift_u64(src_p[5], 32u, 0xffu);
        dst_p->itfc_version_commit |= unpack_left_shift_u64(src_p[6], 40u, 0xffu);
        dst_p->itfc_version_commit |= unpack_left_shift_u64(src_p[7], 48u, 0xffu);
        break;

    default:
        break;
    }

    return (0);
}

int binocan_interface_board_version_init(struct binocan_interface_board_version_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct binocan_interface_board_version_t));

    return 0;
}

uint8_t binocan_interface_board_version_itfc_version_mux_encode(float value)
{
    return (uint8_t)(value);
}

float binocan_interface_board_version_itfc_version_mux_decode(uint8_t value)
{
    return ((float)value);
}

bool binocan_interface_board_version_itfc_version_mux_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t binocan_interface_board_version_itfc_version_dirty_encode(float value)
{
    return (uint8_t)(value);
}

float binocan_interface_board_version_itfc_version_dirty_decode(uint8_t value)
{
    return ((float)value);
}

bool binocan_interface_board_version_itfc_version_dirty_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t binocan_interface_board_version_itfc_version_major_encode(float value)
{
    return (uint8_t)(value);
}

float binocan_interface_board_version_itfc_version_major_decode(uint8_t value)
{
    return ((float)value);
}

bool binocan_interface_board_version_itfc_version_major_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint64_t binocan_interface_board_version_itfc_version_commit_encode(float value)
{
    return (uint64_t)(value);
}

float binocan_interface_board_version_itfc_version_commit_decode(uint64_t value)
{
    return ((float)value);
}

bool binocan_interface_board_version_itfc_version_commit_is_in_range(uint64_t value)
{
    return (value <= 72057594037927904ull);
}

uint8_t binocan_interface_board_version_itfc_version_minor_encode(float value)
{
    return (uint8_t)(value);
}

float binocan_interface_board_version_itfc_version_minor_decode(uint8_t value)
{
    return ((float)value);
}

bool binocan_interface_board_version_itfc_version_minor_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t binocan_interface_board_version_itfc_version_patch_encode(float value)
{
    return (uint8_t)(value);
}

float binocan_interface_board_version_itfc_version_patch_decode(uint8_t value)
{
    return ((float)value);
}

bool binocan_interface_board_version_itfc_version_patch_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int binocan_rd_brd_st_pack(
    uint8_t *dst_p,
    const struct binocan_rd_brd_st_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->rd_board_st, 0u, 0x0fu);

    return (8);
}

int binocan_rd_brd_st_unpack(
    struct binocan_rd_brd_st_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->rd_board_st = unpack_right_shift_u8(src_p[0], 0u, 0x0fu);

    return (0);
}

int binocan_rd_brd_st_init(struct binocan_rd_brd_st_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct binocan_rd_brd_st_t));

    return 0;
}

uint8_t binocan_rd_brd_st_rd_board_st_encode(float value)
{
    return (uint8_t)(value);
}

float binocan_rd_brd_st_rd_board_st_decode(uint8_t value)
{
    return ((float)value);
}

bool binocan_rd_brd_st_rd_board_st_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

int binocan_ld_brd_st_pack(
    uint8_t *dst_p,
    const struct binocan_ld_brd_st_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->ld_board_st, 0u, 0x0fu);

    return (8);
}

int binocan_ld_brd_st_unpack(
    struct binocan_ld_brd_st_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->ld_board_st = unpack_right_shift_u8(src_p[0], 0u, 0x0fu);

    return (0);
}

int binocan_ld_brd_st_init(struct binocan_ld_brd_st_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct binocan_ld_brd_st_t));

    return 0;
}

uint8_t binocan_ld_brd_st_ld_board_st_encode(float value)
{
    return (uint8_t)(value);
}

float binocan_ld_brd_st_ld_board_st_decode(uint8_t value)
{
    return ((float)value);
}

bool binocan_ld_brd_st_ld_board_st_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

int binocan_interface_brd_st_pack(
    uint8_t *dst_p,
    const struct binocan_interface_brd_st_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->en_hi_r_sense_st, 1u, 0x02u);
    dst_p[0] |= pack_left_shift_u8(src_p->itfc_exp_st, 2u, 0x04u);
    dst_p[0] |= pack_left_shift_u8(src_p->itfc_adc_st, 3u, 0x08u);
    dst_p[0] |= pack_left_shift_u8(src_p->en_5_v_aux_st, 4u, 0x10u);
    dst_p[0] |= pack_left_shift_u8(src_p->en_5_v_st, 5u, 0x20u);
    dst_p[0] |= pack_left_shift_u8(src_p->ld_check_alive_st, 6u, 0x40u);
    dst_p[0] |= pack_left_shift_u8(src_p->rd_check_alive_st, 7u, 0x80u);
    dst_p[1] |= pack_left_shift_u8(src_p->itfc_board_st, 5u, 0xe0u);
    dst_p[2] |= pack_left_shift_u8(src_p->mcu_temperature, 1u, 0xfeu);

    return (8);
}

int binocan_interface_brd_st_unpack(
    struct binocan_interface_brd_st_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->en_hi_r_sense_st = unpack_right_shift_u8(src_p[0], 1u, 0x02u);
    dst_p->itfc_exp_st = unpack_right_shift_u8(src_p[0], 2u, 0x04u);
    dst_p->itfc_adc_st = unpack_right_shift_u8(src_p[0], 3u, 0x08u);
    dst_p->en_5_v_aux_st = unpack_right_shift_u8(src_p[0], 4u, 0x10u);
    dst_p->en_5_v_st = unpack_right_shift_u8(src_p[0], 5u, 0x20u);
    dst_p->ld_check_alive_st = unpack_right_shift_u8(src_p[0], 6u, 0x40u);
    dst_p->rd_check_alive_st = unpack_right_shift_u8(src_p[0], 7u, 0x80u);
    dst_p->itfc_board_st = unpack_right_shift_u8(src_p[1], 5u, 0xe0u);
    dst_p->mcu_temperature = unpack_right_shift_u8(src_p[2], 1u, 0xfeu);

    return (0);
}

int binocan_interface_brd_st_init(struct binocan_interface_brd_st_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct binocan_interface_brd_st_t));

    return 0;
}

uint8_t binocan_interface_brd_st_en_hi_r_sense_st_encode(float value)
{
    return (uint8_t)(value);
}

float binocan_interface_brd_st_en_hi_r_sense_st_decode(uint8_t value)
{
    return ((float)value);
}

bool binocan_interface_brd_st_en_hi_r_sense_st_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t binocan_interface_brd_st_itfc_exp_st_encode(float value)
{
    return (uint8_t)(value);
}

float binocan_interface_brd_st_itfc_exp_st_decode(uint8_t value)
{
    return ((float)value);
}

bool binocan_interface_brd_st_itfc_exp_st_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t binocan_interface_brd_st_itfc_adc_st_encode(float value)
{
    return (uint8_t)(value);
}

float binocan_interface_brd_st_itfc_adc_st_decode(uint8_t value)
{
    return ((float)value);
}

bool binocan_interface_brd_st_itfc_adc_st_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t binocan_interface_brd_st_en_5_v_aux_st_encode(float value)
{
    return (uint8_t)(value);
}

float binocan_interface_brd_st_en_5_v_aux_st_decode(uint8_t value)
{
    return ((float)value);
}

bool binocan_interface_brd_st_en_5_v_aux_st_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t binocan_interface_brd_st_en_5_v_st_encode(float value)
{
    return (uint8_t)(value);
}

float binocan_interface_brd_st_en_5_v_st_decode(uint8_t value)
{
    return ((float)value);
}

bool binocan_interface_brd_st_en_5_v_st_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t binocan_interface_brd_st_ld_check_alive_st_encode(float value)
{
    return (uint8_t)(value);
}

float binocan_interface_brd_st_ld_check_alive_st_decode(uint8_t value)
{
    return ((float)value);
}

bool binocan_interface_brd_st_ld_check_alive_st_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t binocan_interface_brd_st_rd_check_alive_st_encode(float value)
{
    return (uint8_t)(value);
}

float binocan_interface_brd_st_rd_check_alive_st_decode(uint8_t value)
{
    return ((float)value);
}

bool binocan_interface_brd_st_rd_check_alive_st_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t binocan_interface_brd_st_itfc_board_st_encode(float value)
{
    return (uint8_t)(value);
}

float binocan_interface_brd_st_itfc_board_st_decode(uint8_t value)
{
    return ((float)value);
}

bool binocan_interface_brd_st_itfc_board_st_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

uint8_t binocan_interface_brd_st_mcu_temperature_encode(float value)
{
    return (uint8_t)(value);
}

float binocan_interface_brd_st_mcu_temperature_decode(uint8_t value)
{
    return ((float)value);
}

bool binocan_interface_brd_st_mcu_temperature_is_in_range(uint8_t value)
{
    return (value <= 127u);
}

int binocan_base_odometer_pack(
    uint8_t *dst_p,
    const struct binocan_base_odometer_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u32(src_p->odometer_km, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->odometer_km, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->odometer_km, 16u, 0x0fu);
    dst_p[2] |= pack_left_shift_u8(src_p->odo_rem_m, 4u, 0xf0u);
    dst_p[3] |= pack_left_shift_u16(src_p->trip_km, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->trip_km, 8u, 0x0fu);
    dst_p[4] |= pack_left_shift_u8(src_p->trip_rem_m, 4u, 0xf0u);

    return (8);
}

int binocan_base_odometer_unpack(
    struct binocan_base_odometer_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->odometer_km = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    dst_p->odometer_km |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    dst_p->odometer_km |= unpack_left_shift_u32(src_p[2], 16u, 0x0fu);
    dst_p->odo_rem_m = unpack_right_shift_u8(src_p[2], 4u, 0xf0u);
    dst_p->trip_km = unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->trip_km |= unpack_left_shift_u16(src_p[4], 8u, 0x0fu);
    dst_p->trip_rem_m = unpack_right_shift_u8(src_p[4], 4u, 0xf0u);

    return (0);
}

int binocan_base_odometer_init(struct binocan_base_odometer_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct binocan_base_odometer_t));

    return 0;
}

uint32_t binocan_base_odometer_odometer_km_encode(float value)
{
    return (uint32_t)(value);
}

float binocan_base_odometer_odometer_km_decode(uint32_t value)
{
    return ((float)value);
}

bool binocan_base_odometer_odometer_km_is_in_range(uint32_t value)
{
    return (value <= 1048575u);
}

uint8_t binocan_base_odometer_odo_rem_m_encode(float value)
{
    return (uint8_t)(value / 100.0f);
}

float binocan_base_odometer_odo_rem_m_decode(uint8_t value)
{
    return ((float)value * 100.0f);
}

bool binocan_base_odometer_odo_rem_m_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint16_t binocan_base_odometer_trip_km_encode(float value)
{
    return (uint16_t)(value);
}

float binocan_base_odometer_trip_km_decode(uint16_t value)
{
    return ((float)value);
}

bool binocan_base_odometer_trip_km_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

uint8_t binocan_base_odometer_trip_rem_m_encode(float value)
{
    return (uint8_t)(value / 100.0f);
}

float binocan_base_odometer_trip_rem_m_decode(uint8_t value)
{
    return ((float)value * 100.0f);
}

bool binocan_base_odometer_trip_rem_m_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

int binocan_extra_chargecooling_metrics_pack(
    uint8_t *dst_p,
    const struct binocan_extra_chargecooling_metrics_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->bitmask, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->charge_coolant_temp_in, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->charge_coolant_temp_out, 0u, 0xffu);

    return (8);
}

int binocan_extra_chargecooling_metrics_unpack(
    struct binocan_extra_chargecooling_metrics_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->bitmask = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->charge_coolant_temp_in = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->charge_coolant_temp_out = unpack_right_shift_u8(src_p[2], 0u, 0xffu);

    return (0);
}

int binocan_extra_chargecooling_metrics_init(struct binocan_extra_chargecooling_metrics_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct binocan_extra_chargecooling_metrics_t));

    return 0;
}

uint8_t binocan_extra_chargecooling_metrics_bitmask_encode(float value)
{
    return (uint8_t)(value);
}

float binocan_extra_chargecooling_metrics_bitmask_decode(uint8_t value)
{
    return ((float)value);
}

bool binocan_extra_chargecooling_metrics_bitmask_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t binocan_extra_chargecooling_metrics_charge_coolant_temp_in_encode(float value)
{
    return (uint8_t)(value);
}

float binocan_extra_chargecooling_metrics_charge_coolant_temp_in_decode(uint8_t value)
{
    return ((float)value);
}

bool binocan_extra_chargecooling_metrics_charge_coolant_temp_in_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t binocan_extra_chargecooling_metrics_charge_coolant_temp_out_encode(float value)
{
    return (uint8_t)(value);
}

float binocan_extra_chargecooling_metrics_charge_coolant_temp_out_decode(uint8_t value)
{
    return ((float)value);
}

bool binocan_extra_chargecooling_metrics_charge_coolant_temp_out_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int binocan_base_active_hi_lo_pack(
    uint8_t *dst_p,
    const struct binocan_base_active_hi_lo_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->ignition_ah_st, 0u, 0x01u);
    dst_p[0] |= pack_left_shift_u8(src_p->hi_beams_ah_tt, 1u, 0x02u);
    dst_p[0] |= pack_left_shift_u8(src_p->alternator_al_tt, 2u, 0x04u);
    dst_p[0] |= pack_left_shift_u8(src_p->brake_low_al_tt, 3u, 0x08u);
    dst_p[0] |= pack_left_shift_u8(src_p->parking_brake_al_tt, 4u, 0x10u);
    dst_p[0] |= pack_left_shift_u8(src_p->oil_pressure_al_tt, 5u, 0x20u);
    dst_p[0] |= pack_left_shift_u8(src_p->airbag_al_tt, 6u, 0x40u);
    dst_p[0] |= pack_left_shift_u8(src_p->cel_al_tt, 7u, 0x80u);
    dst_p[1] |= pack_left_shift_u8(src_p->right_turn_ah_tt, 0u, 0x01u);
    dst_p[1] |= pack_left_shift_u8(src_p->left_turn_ah_tt, 1u, 0x02u);
    dst_p[1] |= pack_left_shift_u8(src_p->abs_al_tt, 2u, 0x04u);
    dst_p[1] |= pack_left_shift_u8(src_p->door_al_tt, 3u, 0x08u);
    dst_p[1] |= pack_left_shift_u8(src_p->coolant_low_al_tt, 4u, 0x10u);
    dst_p[1] |= pack_left_shift_u8(src_p->button_al, 5u, 0x20u);
    dst_p[1] |= pack_left_shift_u8(src_p->alarm_ah, 6u, 0x40u);
    dst_p[1] |= pack_left_shift_u8(src_p->backlight_ah, 7u, 0x80u);
    dst_p[2] |= pack_left_shift_u8(src_p->over_temperature_tt, 0u, 0x01u);
    dst_p[2] |= pack_left_shift_u8(src_p->fuel_low_tt, 1u, 0x02u);

    return (8);
}

int binocan_base_active_hi_lo_unpack(
    struct binocan_base_active_hi_lo_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->ignition_ah_st = unpack_right_shift_u8(src_p[0], 0u, 0x01u);
    dst_p->hi_beams_ah_tt = unpack_right_shift_u8(src_p[0], 1u, 0x02u);
    dst_p->alternator_al_tt = unpack_right_shift_u8(src_p[0], 2u, 0x04u);
    dst_p->brake_low_al_tt = unpack_right_shift_u8(src_p[0], 3u, 0x08u);
    dst_p->parking_brake_al_tt = unpack_right_shift_u8(src_p[0], 4u, 0x10u);
    dst_p->oil_pressure_al_tt = unpack_right_shift_u8(src_p[0], 5u, 0x20u);
    dst_p->airbag_al_tt = unpack_right_shift_u8(src_p[0], 6u, 0x40u);
    dst_p->cel_al_tt = unpack_right_shift_u8(src_p[0], 7u, 0x80u);
    dst_p->right_turn_ah_tt = unpack_right_shift_u8(src_p[1], 0u, 0x01u);
    dst_p->left_turn_ah_tt = unpack_right_shift_u8(src_p[1], 1u, 0x02u);
    dst_p->abs_al_tt = unpack_right_shift_u8(src_p[1], 2u, 0x04u);
    dst_p->door_al_tt = unpack_right_shift_u8(src_p[1], 3u, 0x08u);
    dst_p->coolant_low_al_tt = unpack_right_shift_u8(src_p[1], 4u, 0x10u);
    dst_p->button_al = unpack_right_shift_u8(src_p[1], 5u, 0x20u);
    dst_p->alarm_ah = unpack_right_shift_u8(src_p[1], 6u, 0x40u);
    dst_p->backlight_ah = unpack_right_shift_u8(src_p[1], 7u, 0x80u);
    dst_p->over_temperature_tt = unpack_right_shift_u8(src_p[2], 0u, 0x01u);
    dst_p->fuel_low_tt = unpack_right_shift_u8(src_p[2], 1u, 0x02u);

    return (0);
}

int binocan_base_active_hi_lo_init(struct binocan_base_active_hi_lo_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct binocan_base_active_hi_lo_t));

    return 0;
}

uint8_t binocan_base_active_hi_lo_ignition_ah_st_encode(float value)
{
    return (uint8_t)(value);
}

float binocan_base_active_hi_lo_ignition_ah_st_decode(uint8_t value)
{
    return ((float)value);
}

bool binocan_base_active_hi_lo_ignition_ah_st_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t binocan_base_active_hi_lo_hi_beams_ah_tt_encode(float value)
{
    return (uint8_t)(value);
}

float binocan_base_active_hi_lo_hi_beams_ah_tt_decode(uint8_t value)
{
    return ((float)value);
}

bool binocan_base_active_hi_lo_hi_beams_ah_tt_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t binocan_base_active_hi_lo_alternator_al_tt_encode(float value)
{
    return (uint8_t)(value);
}

float binocan_base_active_hi_lo_alternator_al_tt_decode(uint8_t value)
{
    return ((float)value);
}

bool binocan_base_active_hi_lo_alternator_al_tt_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t binocan_base_active_hi_lo_brake_low_al_tt_encode(float value)
{
    return (uint8_t)(value);
}

float binocan_base_active_hi_lo_brake_low_al_tt_decode(uint8_t value)
{
    return ((float)value);
}

bool binocan_base_active_hi_lo_brake_low_al_tt_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t binocan_base_active_hi_lo_parking_brake_al_tt_encode(float value)
{
    return (uint8_t)(value);
}

float binocan_base_active_hi_lo_parking_brake_al_tt_decode(uint8_t value)
{
    return ((float)value);
}

bool binocan_base_active_hi_lo_parking_brake_al_tt_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t binocan_base_active_hi_lo_oil_pressure_al_tt_encode(float value)
{
    return (uint8_t)(value);
}

float binocan_base_active_hi_lo_oil_pressure_al_tt_decode(uint8_t value)
{
    return ((float)value);
}

bool binocan_base_active_hi_lo_oil_pressure_al_tt_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t binocan_base_active_hi_lo_airbag_al_tt_encode(float value)
{
    return (uint8_t)(value);
}

float binocan_base_active_hi_lo_airbag_al_tt_decode(uint8_t value)
{
    return ((float)value);
}

bool binocan_base_active_hi_lo_airbag_al_tt_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t binocan_base_active_hi_lo_cel_al_tt_encode(float value)
{
    return (uint8_t)(value);
}

float binocan_base_active_hi_lo_cel_al_tt_decode(uint8_t value)
{
    return ((float)value);
}

bool binocan_base_active_hi_lo_cel_al_tt_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t binocan_base_active_hi_lo_right_turn_ah_tt_encode(float value)
{
    return (uint8_t)(value);
}

float binocan_base_active_hi_lo_right_turn_ah_tt_decode(uint8_t value)
{
    return ((float)value);
}

bool binocan_base_active_hi_lo_right_turn_ah_tt_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t binocan_base_active_hi_lo_left_turn_ah_tt_encode(float value)
{
    return (uint8_t)(value);
}

float binocan_base_active_hi_lo_left_turn_ah_tt_decode(uint8_t value)
{
    return ((float)value);
}

bool binocan_base_active_hi_lo_left_turn_ah_tt_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t binocan_base_active_hi_lo_abs_al_tt_encode(float value)
{
    return (uint8_t)(value);
}

float binocan_base_active_hi_lo_abs_al_tt_decode(uint8_t value)
{
    return ((float)value);
}

bool binocan_base_active_hi_lo_abs_al_tt_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t binocan_base_active_hi_lo_door_al_tt_encode(float value)
{
    return (uint8_t)(value);
}

float binocan_base_active_hi_lo_door_al_tt_decode(uint8_t value)
{
    return ((float)value);
}

bool binocan_base_active_hi_lo_door_al_tt_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t binocan_base_active_hi_lo_coolant_low_al_tt_encode(float value)
{
    return (uint8_t)(value);
}

float binocan_base_active_hi_lo_coolant_low_al_tt_decode(uint8_t value)
{
    return ((float)value);
}

bool binocan_base_active_hi_lo_coolant_low_al_tt_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t binocan_base_active_hi_lo_button_al_encode(float value)
{
    return (uint8_t)(value);
}

float binocan_base_active_hi_lo_button_al_decode(uint8_t value)
{
    return ((float)value);
}

bool binocan_base_active_hi_lo_button_al_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t binocan_base_active_hi_lo_alarm_ah_encode(float value)
{
    return (uint8_t)(value);
}

float binocan_base_active_hi_lo_alarm_ah_decode(uint8_t value)
{
    return ((float)value);
}

bool binocan_base_active_hi_lo_alarm_ah_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t binocan_base_active_hi_lo_backlight_ah_encode(float value)
{
    return (uint8_t)(value);
}

float binocan_base_active_hi_lo_backlight_ah_decode(uint8_t value)
{
    return ((float)value);
}

bool binocan_base_active_hi_lo_backlight_ah_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t binocan_base_active_hi_lo_over_temperature_tt_encode(float value)
{
    return (uint8_t)(value);
}

float binocan_base_active_hi_lo_over_temperature_tt_decode(uint8_t value)
{
    return ((float)value);
}

bool binocan_base_active_hi_lo_over_temperature_tt_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t binocan_base_active_hi_lo_fuel_low_tt_encode(float value)
{
    return (uint8_t)(value);
}

float binocan_base_active_hi_lo_fuel_low_tt_decode(uint8_t value)
{
    return ((float)value);
}

bool binocan_base_active_hi_lo_fuel_low_tt_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int binocan_extra_oil_metrics_pack(
    uint8_t *dst_p,
    const struct binocan_extra_oil_metrics_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->bitmask, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->oil_pressure, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->oil_temperature, 0u, 0xffu);

    return (8);
}

int binocan_extra_oil_metrics_unpack(
    struct binocan_extra_oil_metrics_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->bitmask = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->oil_pressure = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->oil_temperature = unpack_right_shift_u8(src_p[2], 0u, 0xffu);

    return (0);
}

int binocan_extra_oil_metrics_init(struct binocan_extra_oil_metrics_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct binocan_extra_oil_metrics_t));

    return 0;
}

uint8_t binocan_extra_oil_metrics_bitmask_encode(float value)
{
    return (uint8_t)(value);
}

float binocan_extra_oil_metrics_bitmask_decode(uint8_t value)
{
    return ((float)value);
}

bool binocan_extra_oil_metrics_bitmask_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t binocan_extra_oil_metrics_oil_pressure_encode(float value)
{
    return (uint8_t)(value / 0.1f);
}

float binocan_extra_oil_metrics_oil_pressure_decode(uint8_t value)
{
    return ((float)value * 0.1f);
}

bool binocan_extra_oil_metrics_oil_pressure_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t binocan_extra_oil_metrics_oil_temperature_encode(float value)
{
    return (uint8_t)(value);
}

float binocan_extra_oil_metrics_oil_temperature_decode(uint8_t value)
{
    return ((float)value);
}

bool binocan_extra_oil_metrics_oil_temperature_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int binocan_base_slow_metrics_pack(
    uint8_t *dst_p,
    const struct binocan_base_slow_metrics_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->coolant_temp, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->fuel_level_pc, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->lv_voltage_v, 0u, 0xffu);

    return (8);
}

int binocan_base_slow_metrics_unpack(
    struct binocan_base_slow_metrics_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->coolant_temp = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->fuel_level_pc = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->lv_voltage_v = unpack_right_shift_u8(src_p[2], 0u, 0xffu);

    return (0);
}

int binocan_base_slow_metrics_init(struct binocan_base_slow_metrics_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct binocan_base_slow_metrics_t));

    return 0;
}

uint8_t binocan_base_slow_metrics_coolant_temp_encode(float value)
{
    return (uint8_t)((value - 70.0f) / 0.4f);
}

float binocan_base_slow_metrics_coolant_temp_decode(uint8_t value)
{
    return (((float)value * 0.4f) + 70.0f);
}

bool binocan_base_slow_metrics_coolant_temp_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t binocan_base_slow_metrics_fuel_level_pc_encode(float value)
{
    return (uint8_t)(value / 0.5f);
}

float binocan_base_slow_metrics_fuel_level_pc_decode(uint8_t value)
{
    return ((float)value * 0.5f);
}

bool binocan_base_slow_metrics_fuel_level_pc_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t binocan_base_slow_metrics_lv_voltage_v_encode(float value)
{
    return (uint8_t)(value / 0.1f);
}

float binocan_base_slow_metrics_lv_voltage_v_decode(uint8_t value)
{
    return ((float)value * 0.1f);
}

bool binocan_base_slow_metrics_lv_voltage_v_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int binocan_base_fast_metrics_pack(
    uint8_t *dst_p,
    const struct binocan_base_fast_metrics_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->rpm, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->rpm, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->speed_kph, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->speed_kph, 8u, 0xffu);

    return (8);
}

int binocan_base_fast_metrics_unpack(
    struct binocan_base_fast_metrics_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->rpm = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->rpm |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->speed_kph = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->speed_kph |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);

    return (0);
}

int binocan_base_fast_metrics_init(struct binocan_base_fast_metrics_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct binocan_base_fast_metrics_t));

    return 0;
}

uint16_t binocan_base_fast_metrics_rpm_encode(float value)
{
    return (uint16_t)(value / 0.14f);
}

float binocan_base_fast_metrics_rpm_decode(uint16_t value)
{
    return ((float)value * 0.14f);
}

bool binocan_base_fast_metrics_rpm_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t binocan_base_fast_metrics_speed_kph_encode(float value)
{
    return (uint16_t)(value / 0.04f);
}

float binocan_base_fast_metrics_speed_kph_decode(uint16_t value)
{
    return ((float)value * 0.04f);
}

bool binocan_base_fast_metrics_speed_kph_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}
