/**
 * @file gear_estimator_params.h
 * @brief Auto-generated Gear Estimation Models for MiniGauge (ESP32 / ESP-IDF)
 * Generated by MiniGauge Gear Estimator Lab from multi-log driving dataset.
 *
 * Models implemented:
 * 1. Gated Heuristic Baseline (zero-float fast table lookup)
 * 2. Kinematic-Conditioned Bayesian Classifier (signed acceleration transitions + loss-of-fix handling)
 * 3. Hidden Markov Model (HMM 6-state transition filter with clutch suppression)
 *
 * DBC Values:
 * 0  = Neutral
 * 1..5 = Forward Gears
 * 14 = Uncertain (clutch depression, transition, or ratio out of band)
 */

#pragma once

#include <stdint.h>
#include <stdbool.h>
#include <math.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @name DBC Gear Position Constants
 * @{
 */
#define GEAR_NEUTRAL           0   /**< Neutral gear position identifier */
#define GEAR_UNCERTAIN         14  /**< Uncertain gear position (clutch depressed, transition, or out-of-band ratio) */
#define GEAR_NUM_FORWARD_GEARS 5   /**< Number of modeled forward transmission gears */
#define GEAR_TOLERANCE_ABS     (0.25f)  /**< Maximum absolute ratio tolerance for heuristic matching */
#define GEAR_MIN_SPEED_HZ      (11.28f) /**< Minimum wheel speed pulse frequency to attempt gear estimation (~10 km/h) */
#define GEAR_MIN_RPM_HZ        (33.33f) /**< Minimum engine RPM pulse frequency to attempt gear estimation (~1000 RPM) */
/** @} */

/**
 * @brief Calibrated mean ratio (speed_freq / rpm_freq) for forward gears 1 to 5.
 */
static const float GEAR_RATIO_MEANS[GEAR_NUM_FORWARD_GEARS] = { 1.0180f, 1.7930f, 2.7260f, 3.7630f, 4.5420f };

/**
 * @brief Calibrated ratio Gaussian distribution variance for forward gears 1 to 5.
 */
static const float GEAR_RATIO_VARS[GEAR_NUM_FORWARD_GEARS]  = { 0.01701f, 0.01077f, 0.00584f, 0.00206f, 0.00193f };

/**
 * @brief Empirical 6x6 State Transition Probability Matrix A (Neutral, 1G, 2G, 3G, 4G, 5G).
 */
static const float GEAR_HMM_TRANSITION[6][6] = {
    { 0.9494f, 0.0086f, 0.0092f, 0.0113f, 0.0101f, 0.0113f },
    { 0.0361f, 0.9540f, 0.0025f, 0.0025f, 0.0025f, 0.0025f },
    { 0.0253f, 0.0017f, 0.9679f, 0.0017f, 0.0017f, 0.0017f },
    { 0.0206f, 0.0011f, 0.0011f, 0.9750f, 0.0011f, 0.0011f },
    { 0.0087f, 0.0004f, 0.0004f, 0.0004f, 0.9893f, 0.0007f },
    { 0.0093f, 0.0006f, 0.0006f, 0.0006f, 0.0027f, 0.9863f }
};

/* -------------------------------------------------------------------------- */
/* Model 1: Calibrated Gated Heuristic Baseline                               */
/* -------------------------------------------------------------------------- */

/**
 * @brief State structure for the calibrated gated heuristic gear estimator.
 */
typedef struct {
    float latched_ratio_ema; /**< Exponential moving average of speed/RPM ratio */
    uint8_t latched_gear;    /**< Current debounced and latched gear position */
    uint8_t pending_gear;    /**< Candidate gear undergoing persistence debounce */
    float pending_time_ms;   /**< Accumulated persistence duration for pending gear in milliseconds */
    float prev_ratio;        /**< Previous instantaneous speed/RPM ratio */
} gear_heuristic_state_t;

/**
 * @brief Initialize the gated heuristic gear estimator state.
 *
 * @param[out] st Pointer to heuristic estimator state structure to initialize.
 *
 * @note Thread Safety: Must be called before concurrent calls to gear_heuristic_update().
 * @note Side Effects: Resets latched and pending gear to GEAR_NEUTRAL and zeroes ratio filters.
 */
static inline void gear_heuristic_init(gear_heuristic_state_t *st) {
    st->latched_ratio_ema = 0.0f;
    st->latched_gear = GEAR_NEUTRAL;
    st->pending_gear = GEAR_NEUTRAL;
    st->pending_time_ms = 0.0f;
    st->prev_ratio = 0.0f;
}

/**
 * @brief Update heuristic gear estimation based on speed and RPM pulse frequencies.
 *
 * @param[in,out] st Pointer to heuristic estimator state structure.
 * @param[in] speed_freq Instantaneous wheel speed capture pulse frequency in Hz.
 * @param[in] rpm_freq Instantaneous engine ignition capture pulse frequency in Hz.
 * @param[in] dt_s Sample delta time in seconds.
 *
 * @return uint8_t Currently latched gear position (GEAR_NEUTRAL, 1..5, or GEAR_UNCERTAIN).
 *
 * @note Thread Safety: Reads and modifies state in place; caller must serialize updates.
 * @note Side Effects: Updates ratio EMA, persistence timers, and latched_gear.
 */
static inline uint8_t gear_heuristic_update(gear_heuristic_state_t *st, float speed_freq, float rpm_freq, float dt_s) {
    if (speed_freq < GEAR_MIN_SPEED_HZ || rpm_freq < GEAR_MIN_RPM_HZ) {
        st->latched_gear = GEAR_NEUTRAL;
        st->pending_gear = GEAR_NEUTRAL;
        st->pending_time_ms = 0.0f;
        st->latched_ratio_ema = 0.0f;
        return GEAR_NEUTRAL;
    }

    float r = speed_freq / rpm_freq;
    bool stable = (st->prev_ratio <= 0.0f) || (fabsf(r - st->prev_ratio) <= 0.050f);
    st->prev_ratio = r;

    if (!stable) {
        return st->latched_gear;
    }

    if (st->latched_ratio_ema <= 0.0f) {
        st->latched_ratio_ema = r;
    } else {
        st->latched_ratio_ema = 0.15f * r + 0.85f * st->latched_ratio_ema;
    }

    uint8_t cand = GEAR_UNCERTAIN;
    for (int gi = 0; gi < GEAR_NUM_FORWARD_GEARS; gi++) {
        float nom = GEAR_RATIO_MEANS[gi];
        float max_tol = GEAR_TOLERANCE_ABS;
        if (gi > 0) {
            float d_prev = (nom - GEAR_RATIO_MEANS[gi - 1]) * 0.48f;
            if (d_prev < max_tol) max_tol = d_prev;
        }
        if (gi < GEAR_NUM_FORWARD_GEARS - 1) {
            float d_next = (GEAR_RATIO_MEANS[gi + 1] - nom) * 0.48f;
            if (d_next < max_tol) max_tol = d_next;
        }
        if (fabsf(st->latched_ratio_ema - nom) <= max_tol) {
            cand = (uint8_t)(gi + 1);
            break;
        }
    }

    if (cand != st->pending_gear) {
        st->pending_gear = cand;
        st->pending_time_ms = 0.0f;
    } else {
        st->pending_time_ms += (dt_s * 1000.0f);
        if (st->pending_time_ms >= 200.0f) {
            st->latched_gear = st->pending_gear;
        }
    }

    return st->latched_gear;
}

/* -------------------------------------------------------------------------- */
/* Model 2: Kinematic-Conditioned Bayesian Classifier                         */
/* -------------------------------------------------------------------------- */

/**
 * @brief State structure for the kinematic-conditioned Bayesian gear classifier.
 */
typedef struct {
    float prior[6];        /**< Prior probability distribution vector over 6 states (Neutral, 1G..5G) */
    float prev_speed_freq; /**< Previous wheel speed pulse frequency in Hz for derivative calculation */
    float prev_rpm_freq;   /**< Previous engine RPM pulse frequency in Hz for derivative calculation */
    uint8_t latched_gear;  /**< Currently debounced and latched gear position */
    uint8_t pending_gear;  /**< Candidate gear undergoing persistence debounce */
    float pending_time_ms; /**< Accumulated persistence duration for pending gear in milliseconds */
} gear_bayesian_state_t;

/**
 * @brief Initialize the kinematic-conditioned Bayesian gear classifier state.
 *
 * @param[out] st Pointer to Bayesian classifier state structure to initialize.
 *
 * @note Thread Safety: Must be called before concurrent calls to gear_bayesian_update().
 * @note Side Effects: Sets prior[0]=0.90 (Neutral) and prior[1..5]=0.02; zeroes derivative history.
 */
static inline void gear_bayesian_init(gear_bayesian_state_t *st) {
    st->prior[0] = 0.90f;
    for (int i = 1; i < 6; i++) st->prior[i] = 0.02f;
    st->prev_speed_freq = 0.0f;
    st->prev_rpm_freq = 0.0f;
    st->latched_gear = GEAR_NEUTRAL;
    st->pending_gear = GEAR_NEUTRAL;
    st->pending_time_ms = 0.0f;
}

/**
 * @brief Execute a single update step of the kinematic Bayesian gear classifier.
 *
 * Evaluates speed/RPM kinematic derivatives, dynamically constructs a 6x6 transition matrix,
 * evaluates Gaussian likelihood densities across forward gears, applies clutch-drop suppression,
 * computes the posterior distribution, and debounces candidates with 200 ms persistence.
 *
 * @param[in,out] st Pointer to Bayesian estimator state structure.
 * @param[in] speed_freq Instantaneous wheel speed capture pulse frequency in Hz.
 * @param[in] rpm_freq Instantaneous engine ignition capture pulse frequency in Hz.
 * @param[in] dt_s Sample delta time in seconds.
 *
 * @return uint8_t Currently latched gear position (GEAR_NEUTRAL, 1..5, or GEAR_UNCERTAIN).
 *
 * @note Thread Safety: Reads and modifies state in place; caller must serialize task execution.
 * @note Side Effects: Updates prior probability vector, frequency derivatives, and latched_gear.
 */
static inline uint8_t gear_bayesian_update(gear_bayesian_state_t *st, float speed_freq, float rpm_freq, float dt_s) {
    if (speed_freq < GEAR_MIN_SPEED_HZ || rpm_freq < GEAR_MIN_RPM_HZ) {
        st->prior[0] = 0.95f;
        for (int i = 1; i < 6; i++) st->prior[i] = 0.01f;
        st->prev_speed_freq = speed_freq;
        st->prev_rpm_freq = rpm_freq;
        st->latched_gear = GEAR_NEUTRAL;
        st->pending_gear = GEAR_NEUTRAL;
        st->pending_time_ms = 0.0f;
        return GEAR_NEUTRAL;
    }

    float dt = (dt_s > 0.005f) ? dt_s : 0.05f;
    float dsf = (st->prev_speed_freq > 0.0f) ? ((speed_freq - st->prev_speed_freq) / dt) : 0.0f;
    float drf = (st->prev_rpm_freq > 0.0f) ? ((rpm_freq - st->prev_rpm_freq) / dt) : 0.0f;
    st->prev_speed_freq = speed_freq;
    st->prev_rpm_freq = rpm_freq;

    /* Construct dynamic Kinematic Transition Matrix T[6][6] */
    float T[6][6];
    for (int i = 0; i < 6; i++) {
        for (int j = 0; j < 6; j++) T[i][j] = 0.02f;
    }
    T[0][0] = 0.85f;
    for (int k = 1; k < 6; k++) {
        T[0][k] = 0.03f;
        T[k][k] = 0.96f;
        T[k][0] = 0.03f;
        if (dsf >= 0.0f && rpm_freq >= 55.0f) {
            if (k < 5) T[k][k + 1] = 0.06f;
            if (k > 1) T[k][k - 1] = 0.0001f;
        } else if (dsf < -3.0f) {
            if (k > 1) T[k][k - 1] = 0.06f;
            if (k < 5) T[k][k + 1] = 0.0001f;
        } else {
            if (k < 5) T[k][k + 1] = 0.02f;
            if (k > 1) T[k][k - 1] = 0.02f;
        }
    }

    for (int i = 0; i < 6; i++) {
        float rsum = 0.0f;
        for (int j = 0; j < 6; j++) rsum += T[i][j];
        float inv_sum = 1.0f / rsum;
        for (int j = 0; j < 6; j++) T[i][j] *= inv_sum;
    }

    float pred[6];
    for (int j = 0; j < 6; j++) {
        pred[j] = 0.0f;
        for (int i = 0; i < 6; i++) pred[j] += st->prior[i] * T[i][j];
    }

    float r = speed_freq / rpm_freq;
    bool is_clutch_drop = (drf < -35.0f && speed_freq >= GEAR_MIN_SPEED_HZ && dsf > -5.0f);
    float lik[6];
    lik[0] = 0.08f * (is_clutch_drop ? 1.8f : 1.0f);

    int curr_assumed = 0;
    float max_sub = 0.3f;
    for (int i = 1; i < 6; i++) {
        if (st->prior[i] > max_sub) {
            max_sub = st->prior[i];
            curr_assumed = i;
        }
    }

    for (int gi = 0; gi < 5; gi++) {
        float diff = r - GEAR_RATIO_MEANS[gi];
        float v = GEAR_RATIO_VARS[gi];
        float density = expf(-0.5f * (diff * diff) / v) / sqrtf(6.2831853f * v);
        if (is_clutch_drop && (gi + 1) > curr_assumed && curr_assumed > 0) {
            density *= 0.0001f;
        }
        lik[gi + 1] = density;
    }

    const float decay = 0.94f;
    float post[6];
    float tot = 0.0f;
    for (int k = 0; k < 6; k++) {
        post[k] = lik[k] * (decay * pred[k] + (1.0f - decay) * 0.1666f);
        tot += post[k];
    }

    uint8_t raw_choice = GEAR_UNCERTAIN;
    if (tot > 0.00001f) {
        float inv = 1.0f / tot;
        float max_p = 0.0f;
        int best_k = 0;
        for (int k = 0; k < 6; k++) {
            st->prior[k] = post[k] * inv;
            if (st->prior[k] > max_p) {
                max_p = st->prior[k];
                best_k = k;
            }
        }
        if (max_p >= 0.38f) {
            raw_choice = (best_k == 0) ? GEAR_UNCERTAIN : (uint8_t)best_k;
        } else {
            raw_choice = GEAR_UNCERTAIN;
        }
    }

    if (is_clutch_drop && raw_choice > st->latched_gear && st->latched_gear > 0 && st->latched_gear <= 5) {
        raw_choice = st->latched_gear;
    }

    if (raw_choice != st->pending_gear) {
        st->pending_gear = raw_choice;
        st->pending_time_ms = 0.0f;
    } else {
        st->pending_time_ms += (dt * 1000.0f);
        if (st->pending_time_ms >= 200.0f) {
            st->latched_gear = st->pending_gear;
        }
    }

    return st->latched_gear;
}

/* -------------------------------------------------------------------------- */
/* Model 3: Hidden Markov Model (HMM) with Clutch Suppression                 */
/* -------------------------------------------------------------------------- */

/**
 * @brief State structure for the 6-state Hidden Markov Model (HMM) gear estimator.
 */
typedef struct {
    float alpha[6];      /**< Forward inference belief state vector across 6 states (Neutral, 1G..5G) */
    float prev_rpm_freq; /**< Previous engine RPM pulse frequency in Hz for clutch drop detection */
    uint8_t prev_gear;   /**< Previously inferred gear state */
} gear_hmm_state_t;

/**
 * @brief Initialize the Hidden Markov Model (HMM) gear estimator state.
 *
 * @param[out] st Pointer to HMM estimator state structure to initialize.
 *
 * @note Thread Safety: Must be called before concurrent calls to gear_hmm_update().
 * @note Side Effects: Sets alpha[0]=1.0 (Neutral) and alpha[1..5]=0.0; zeroes RPM frequency.
 */
static inline void gear_hmm_init(gear_hmm_state_t *st) {
    st->alpha[0] = 1.0f;
    for (int i = 1; i < 6; i++) st->alpha[i] = 0.0f;
    st->prev_rpm_freq = 0.0f;
    st->prev_gear = GEAR_NEUTRAL;
}

/**
 * @brief Execute forward inference step for the 6-state HMM gear estimator.
 *
 * @param[in,out] st Pointer to HMM estimator state structure.
 * @param[in] speed_freq Instantaneous wheel speed capture pulse frequency in Hz.
 * @param[in] rpm_freq Instantaneous engine ignition capture pulse frequency in Hz.
 * @param[in] dt_s Sample delta time in seconds.
 *
 * @return uint8_t Inferred gear position (GEAR_NEUTRAL, 1..5, or GEAR_UNCERTAIN).
 *
 * @note Thread Safety: Reads and modifies state in place; caller must serialize task execution.
 * @note Side Effects: Updates forward alpha state vector and prev_rpm_freq.
 */
static inline uint8_t gear_hmm_update(gear_hmm_state_t *st, float speed_freq, float rpm_freq, float dt_s) {
    if (speed_freq < GEAR_MIN_SPEED_HZ || rpm_freq < GEAR_MIN_RPM_HZ) {
        st->alpha[0] = 0.95f;
        for (int i = 1; i < 6; i++) st->alpha[i] = 0.01f;
        st->prev_rpm_freq = rpm_freq;
        st->prev_gear = GEAR_NEUTRAL;
        return GEAR_NEUTRAL;
    }

    float r = speed_freq / rpm_freq;
    float dt = (dt_s > 0.005f) ? dt_s : 0.05f;
    float drpm = (st->prev_rpm_freq > 0.0f) ? ((rpm_freq - st->prev_rpm_freq) / dt) : 0.0f;
    st->prev_rpm_freq = rpm_freq;

    bool is_clutch_drop = (drpm < -40.0f); /* Fast engine drop */
    float emiss[6];
    emiss[0] = is_clutch_drop ? 0.180f : 0.040f;

    for (int gi = 0; gi < 5; gi++) {
        float diff = r - GEAR_RATIO_MEANS[gi];
        float v = GEAR_RATIO_VARS[gi];
        float dens = expf(-0.5f * (diff * diff) / v) / sqrtf(6.2831853f * v);
        /* Suppress higher phantom gears while engine is falling toward idle */
        if (is_clutch_drop && (gi + 1) > st->prev_gear && st->prev_gear > 0 && st->prev_gear <= 5) {
            dens *= 0.0001f;
        }
        emiss[gi + 1] = dens;
    }

    float new_alpha[6];
    float tot = 0.0f;

    for (int j = 0; j < 6; j++) {
        float s = 0.0f;
        for (int k = 0; k < 6; k++) {
            s += st->alpha[k] * GEAR_HMM_TRANSITION[k][j];
        }
        new_alpha[j] = s * emiss[j];
        tot += new_alpha[j];
    }

    uint8_t best_j = GEAR_UNCERTAIN;
    float max_a = 0.0f;

    if (tot > 0.00001f) {
        float inv = 1.0f / tot;
        for (int j = 0; j < 6; j++) {
            st->alpha[j] = new_alpha[j] * inv;
            if (st->alpha[j] > max_a) {
                max_a = st->alpha[j];
                best_j = (uint8_t)j;
            }
        }
    }

    uint8_t result = GEAR_UNCERTAIN;
    if (max_a >= 0.38f) {
        result = (best_j == 0) ? GEAR_UNCERTAIN : best_j;
    } else {
        result = GEAR_UNCERTAIN;
    }

    st->prev_gear = result;
    return result;
}

#ifdef __cplusplus
}
#endif
