/**
 * @file binocan.h
 *
 * @brief This header file was generated by cantools version 41.0.0 Thu Dec 18 19:57:14 2025.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef BINOCAN_H
#define BINOCAN_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifndef EINVAL
#    define EINVAL 22
#endif

/* Frame ids. */
#define BINOCAN_RDB_BOARD_VERSION_FRAME_ID (0x132u)
#define BINOCAN_LDB_BOARD_VERSION_FRAME_ID (0x131u)
#define BINOCAN_EXT_UDS_RESP_FRAME_ID (0x787u)
#define BINOCAN_EXT_UDS_REQ_FRAME_ID (0x786u)
#define BINOCAN_RDB_UDS_RESP_FRAME_ID (0x785u)
#define BINOCAN_RDB_UDS_REQ_FRAME_ID (0x784u)
#define BINOCAN_LDB_UDS_RESP_FRAME_ID (0x783u)
#define BINOCAN_LDB_UDS_REQ_FRAME_ID (0x782u)
#define BINOCAN_ITF_UDS_RESP_FRAME_ID (0x781u)
#define BINOCAN_ITF_UDS_REQ_FRAME_ID (0x780u)
#define BINOCAN_ITF_BOARD_VERSION_FRAME_ID (0x130u)
#define BINOCAN_RDB_ST_FRAME_ID (0x122u)
#define BINOCAN_LDB_ST_FRAME_ID (0x121u)
#define BINOCAN_ITF_BOARD_ST_FRAME_ID (0x120u)
#define BINOCAN_ITF_ODOMETER_FRAME_ID (0x111u)
#define BINOCAN_EXT_CHARGECOOLING_METRICS_FRAME_ID (0x201u)
#define BINOCAN_ITF_ACTIVE_HI_LO_FRAME_ID (0x101u)
#define BINOCAN_EXT_OIL_METRICS_FRAME_ID (0x200u)
#define BINOCAN_ITF_SLOW_METRICS_FRAME_ID (0x110u)
#define BINOCAN_ITF_FAST_METRICS_FRAME_ID (0x100u)

/* Frame lengths in bytes. */
#define BINOCAN_RDB_BOARD_VERSION_LENGTH (8u)
#define BINOCAN_LDB_BOARD_VERSION_LENGTH (8u)
#define BINOCAN_EXT_UDS_RESP_LENGTH (8u)
#define BINOCAN_EXT_UDS_REQ_LENGTH (8u)
#define BINOCAN_RDB_UDS_RESP_LENGTH (8u)
#define BINOCAN_RDB_UDS_REQ_LENGTH (8u)
#define BINOCAN_LDB_UDS_RESP_LENGTH (8u)
#define BINOCAN_LDB_UDS_REQ_LENGTH (8u)
#define BINOCAN_ITF_UDS_RESP_LENGTH (8u)
#define BINOCAN_ITF_UDS_REQ_LENGTH (8u)
#define BINOCAN_ITF_BOARD_VERSION_LENGTH (8u)
#define BINOCAN_RDB_ST_LENGTH (8u)
#define BINOCAN_LDB_ST_LENGTH (8u)
#define BINOCAN_ITF_BOARD_ST_LENGTH (8u)
#define BINOCAN_ITF_ODOMETER_LENGTH (8u)
#define BINOCAN_EXT_CHARGECOOLING_METRICS_LENGTH (8u)
#define BINOCAN_ITF_ACTIVE_HI_LO_LENGTH (8u)
#define BINOCAN_EXT_OIL_METRICS_LENGTH (8u)
#define BINOCAN_ITF_SLOW_METRICS_LENGTH (8u)
#define BINOCAN_ITF_FAST_METRICS_LENGTH (8u)

/* Extended or standard frame types. */
#define BINOCAN_RDB_BOARD_VERSION_IS_EXTENDED (0)
#define BINOCAN_LDB_BOARD_VERSION_IS_EXTENDED (0)
#define BINOCAN_EXT_UDS_RESP_IS_EXTENDED (0)
#define BINOCAN_EXT_UDS_REQ_IS_EXTENDED (0)
#define BINOCAN_RDB_UDS_RESP_IS_EXTENDED (0)
#define BINOCAN_RDB_UDS_REQ_IS_EXTENDED (0)
#define BINOCAN_LDB_UDS_RESP_IS_EXTENDED (0)
#define BINOCAN_LDB_UDS_REQ_IS_EXTENDED (0)
#define BINOCAN_ITF_UDS_RESP_IS_EXTENDED (0)
#define BINOCAN_ITF_UDS_REQ_IS_EXTENDED (0)
#define BINOCAN_ITF_BOARD_VERSION_IS_EXTENDED (0)
#define BINOCAN_RDB_ST_IS_EXTENDED (0)
#define BINOCAN_LDB_ST_IS_EXTENDED (0)
#define BINOCAN_ITF_BOARD_ST_IS_EXTENDED (0)
#define BINOCAN_ITF_ODOMETER_IS_EXTENDED (0)
#define BINOCAN_EXT_CHARGECOOLING_METRICS_IS_EXTENDED (0)
#define BINOCAN_ITF_ACTIVE_HI_LO_IS_EXTENDED (0)
#define BINOCAN_EXT_OIL_METRICS_IS_EXTENDED (0)
#define BINOCAN_ITF_SLOW_METRICS_IS_EXTENDED (0)
#define BINOCAN_ITF_FAST_METRICS_IS_EXTENDED (0)

/* Frame cycle times in milliseconds. */
#define BINOCAN_RDB_BOARD_VERSION_CYCLE_TIME_MS (1000u)
#define BINOCAN_LDB_BOARD_VERSION_CYCLE_TIME_MS (1000u)
#define BINOCAN_EXT_UDS_RESP_CYCLE_TIME_MS (100u)
#define BINOCAN_EXT_UDS_REQ_CYCLE_TIME_MS (100u)
#define BINOCAN_RDB_UDS_RESP_CYCLE_TIME_MS (100u)
#define BINOCAN_RDB_UDS_REQ_CYCLE_TIME_MS (100u)
#define BINOCAN_LDB_UDS_RESP_CYCLE_TIME_MS (100u)
#define BINOCAN_LDB_UDS_REQ_CYCLE_TIME_MS (100u)
#define BINOCAN_ITF_UDS_RESP_CYCLE_TIME_MS (100u)
#define BINOCAN_ITF_UDS_REQ_CYCLE_TIME_MS (100u)
#define BINOCAN_ITF_BOARD_VERSION_CYCLE_TIME_MS (1000u)
#define BINOCAN_RDB_ST_CYCLE_TIME_MS (200u)
#define BINOCAN_LDB_ST_CYCLE_TIME_MS (200u)
#define BINOCAN_ITF_BOARD_ST_CYCLE_TIME_MS (200u)
#define BINOCAN_ITF_ODOMETER_CYCLE_TIME_MS (250u)
#define BINOCAN_EXT_CHARGECOOLING_METRICS_CYCLE_TIME_MS (100u)
#define BINOCAN_ITF_ACTIVE_HI_LO_CYCLE_TIME_MS (200u)
#define BINOCAN_EXT_OIL_METRICS_CYCLE_TIME_MS (100u)
#define BINOCAN_ITF_SLOW_METRICS_CYCLE_TIME_MS (500u)
#define BINOCAN_ITF_FAST_METRICS_CYCLE_TIME_MS (100u)

/* Signal choices. */
#define BINOCAN_RDB_BOARD_VERSION_RDB_VERSION_MUX_BASE_VERSION_TAG_AND_DIRTY_FLAG_CHOICE (0u)
#define BINOCAN_RDB_BOARD_VERSION_RDB_VERSION_MUX_COMMIT_ID_CHOICE (1u)

#define BINOCAN_LDB_BOARD_VERSION_LDB_VERSION_MUX_BASE_VERSION_TAG_AND_DIRTY_FLAG_CHOICE (0u)
#define BINOCAN_LDB_BOARD_VERSION_LDB_VERSION_MUX_COMMIT_ID_CHOICE (1u)

#define BINOCAN_ITF_BOARD_VERSION_ITF_VERSION_MUX_BASE_VERSION_TAG_AND_DIRTY_FLAG_CHOICE (0u)
#define BINOCAN_ITF_BOARD_VERSION_ITF_VERSION_MUX_COMMIT_ID_CHOICE (1u)

#define BINOCAN_RDB_ST_RDB_SM_ST_OFF_CHOICE (0u)
#define BINOCAN_RDB_ST_RDB_SM_ST_INIT_CHOICE (1u)
#define BINOCAN_RDB_ST_RDB_SM_ST_OK_CHOICE (2u)
#define BINOCAN_RDB_ST_RDB_SM_ST_DEGRADED_CHOICE (3u)
#define BINOCAN_RDB_ST_RDB_SM_ST_FAULT_CHOICE (4u)
#define BINOCAN_RDB_ST_RDB_SM_ST_OTA_CHOICE (5u)
#define BINOCAN_RDB_ST_RDB_SM_ST_FACTORY_CHOICE (7u)

#define BINOCAN_LDB_ST_LDB_SM_ST_OFF_CHOICE (0u)
#define BINOCAN_LDB_ST_LDB_SM_ST_INIT_CHOICE (1u)
#define BINOCAN_LDB_ST_LDB_SM_ST_OK_CHOICE (2u)
#define BINOCAN_LDB_ST_LDB_SM_ST_DEGRADED_CHOICE (3u)
#define BINOCAN_LDB_ST_LDB_SM_ST_FAULT_CHOICE (4u)
#define BINOCAN_LDB_ST_LDB_SM_ST_OTA_CHOICE (5u)
#define BINOCAN_LDB_ST_LDB_SM_ST_FACTORY_CHOICE (7u)

#define BINOCAN_ITF_BOARD_ST_ITF_HI_R_SENSE_ST_OFF_CHOICE (0u)
#define BINOCAN_ITF_BOARD_ST_ITF_HI_R_SENSE_ST_ON_CHOICE (1u)

#define BINOCAN_ITF_BOARD_ST_ITF_EXPANDER_ST_OFF_CHOICE (0u)
#define BINOCAN_ITF_BOARD_ST_ITF_EXPANDER_ST_ON_CHOICE (1u)

#define BINOCAN_ITF_BOARD_ST_ITF_ADC_ST_OFF_CHOICE (0u)
#define BINOCAN_ITF_BOARD_ST_ITF_ADC_ST_ON_CHOICE (1u)

#define BINOCAN_ITF_BOARD_ST_ITF_5_V_AUX_ST_OFF_CHOICE (0u)
#define BINOCAN_ITF_BOARD_ST_ITF_5_V_AUX_ST_ON_CHOICE (1u)

#define BINOCAN_ITF_BOARD_ST_ITF_5_V_ST_OFF_CHOICE (0u)
#define BINOCAN_ITF_BOARD_ST_ITF_5_V_ST_ON_CHOICE (1u)

#define BINOCAN_ITF_BOARD_ST_ITF_LD_CHECK_ALIVE_ST_OFF_CHOICE (0u)
#define BINOCAN_ITF_BOARD_ST_ITF_LD_CHECK_ALIVE_ST_ON_CHOICE (1u)

#define BINOCAN_ITF_BOARD_ST_ITF_RD_CHECK_ALIVE_ST_OFF_CHOICE (0u)
#define BINOCAN_ITF_BOARD_ST_ITF_RD_CHECK_ALIVE_ST_ON_CHOICE (1u)

#define BINOCAN_ITF_BOARD_ST_ITF_SM_ST_OFF_CHOICE (0u)
#define BINOCAN_ITF_BOARD_ST_ITF_SM_ST_INIT_CHOICE (1u)
#define BINOCAN_ITF_BOARD_ST_ITF_SM_ST_OK_CHOICE (2u)
#define BINOCAN_ITF_BOARD_ST_ITF_SM_ST_DEGRADED_CHOICE (3u)
#define BINOCAN_ITF_BOARD_ST_ITF_SM_ST_FAULT_CHOICE (4u)
#define BINOCAN_ITF_BOARD_ST_ITF_SM_ST_OTA_CHOICE (5u)
#define BINOCAN_ITF_BOARD_ST_ITF_SM_ST_FACTORY_CHOICE (7u)

#define BINOCAN_ITF_ACTIVE_HI_LO_ITF_IGNITION_AH_ST_OFF_CHOICE (0u)
#define BINOCAN_ITF_ACTIVE_HI_LO_ITF_IGNITION_AH_ST_ON_CHOICE (1u)

#define BINOCAN_ITF_ACTIVE_HI_LO_ITF_HI_BEAMS_AH_TT_OFF_CHOICE (0u)
#define BINOCAN_ITF_ACTIVE_HI_LO_ITF_HI_BEAMS_AH_TT_ON_CHOICE (1u)

#define BINOCAN_ITF_ACTIVE_HI_LO_ITF_ALTERNATOR_AL_TT_OFF_CHOICE (0u)
#define BINOCAN_ITF_ACTIVE_HI_LO_ITF_ALTERNATOR_AL_TT_ON_CHOICE (1u)

#define BINOCAN_ITF_ACTIVE_HI_LO_ITF_BRAKE_LOW_AL_TT_OFF_CHOICE (0u)
#define BINOCAN_ITF_ACTIVE_HI_LO_ITF_BRAKE_LOW_AL_TT_ON_CHOICE (1u)

#define BINOCAN_ITF_ACTIVE_HI_LO_ITF_PARKING_BRAKE_AL_TT_OFF_CHOICE (0u)
#define BINOCAN_ITF_ACTIVE_HI_LO_ITF_PARKING_BRAKE_AL_TT_ON_CHOICE (1u)

#define BINOCAN_ITF_ACTIVE_HI_LO_ITF_OIL_PRESSURE_AL_TT_OFF_CHOICE (0u)
#define BINOCAN_ITF_ACTIVE_HI_LO_ITF_OIL_PRESSURE_AL_TT_ON_CHOICE (1u)

#define BINOCAN_ITF_ACTIVE_HI_LO_ITF_AIRBAG_AL_TT_OFF_CHOICE (0u)
#define BINOCAN_ITF_ACTIVE_HI_LO_ITF_AIRBAG_AL_TT_ON_CHOICE (1u)

#define BINOCAN_ITF_ACTIVE_HI_LO_ITF_CEL_AL_TT_OFF_CHOICE (0u)
#define BINOCAN_ITF_ACTIVE_HI_LO_ITF_CEL_AL_TT_ON_CHOICE (1u)

#define BINOCAN_ITF_ACTIVE_HI_LO_ITF_RIGHT_TURN_AH_TT_OFF_CHOICE (0u)
#define BINOCAN_ITF_ACTIVE_HI_LO_ITF_RIGHT_TURN_AH_TT_ON_CHOICE (1u)

#define BINOCAN_ITF_ACTIVE_HI_LO_ITF_LEFT_TURN_AH_TT_OFF_CHOICE (0u)
#define BINOCAN_ITF_ACTIVE_HI_LO_ITF_LEFT_TURN_AH_TT_ON_CHOICE (1u)

#define BINOCAN_ITF_ACTIVE_HI_LO_ITF_ABS_AL_TT_OFF_CHOICE (0u)
#define BINOCAN_ITF_ACTIVE_HI_LO_ITF_ABS_AL_TT_ON_CHOICE (1u)

#define BINOCAN_ITF_ACTIVE_HI_LO_ITF_DOOR_AL_TT_OFF_CHOICE (0u)
#define BINOCAN_ITF_ACTIVE_HI_LO_ITF_DOOR_AL_TT_ON_CHOICE (1u)

#define BINOCAN_ITF_ACTIVE_HI_LO_ITF_COOLANT_LOW_AH_TT_OFF_CHOICE (0u)
#define BINOCAN_ITF_ACTIVE_HI_LO_ITF_COOLANT_LOW_AH_TT_ON_CHOICE (1u)

#define BINOCAN_ITF_ACTIVE_HI_LO_ITF_BUTTON_AL_OFF_CHOICE (0u)
#define BINOCAN_ITF_ACTIVE_HI_LO_ITF_BUTTON_AL_ON_CHOICE (1u)

#define BINOCAN_ITF_ACTIVE_HI_LO_ITF_ALARM_AH_OFF_CHOICE (0u)
#define BINOCAN_ITF_ACTIVE_HI_LO_ITF_ALARM_AH_ON_CHOICE (1u)

#define BINOCAN_ITF_ACTIVE_HI_LO_ITF_BACKLIGHT_AH_OFF_CHOICE (0u)
#define BINOCAN_ITF_ACTIVE_HI_LO_ITF_BACKLIGHT_AH_ON_CHOICE (1u)

#define BINOCAN_ITF_ACTIVE_HI_LO_ITF_OVER_TEMPERATURE_TT_OFF_CHOICE (0u)
#define BINOCAN_ITF_ACTIVE_HI_LO_ITF_OVER_TEMPERATURE_TT_ON_CHOICE (1u)

#define BINOCAN_ITF_ACTIVE_HI_LO_ITF_FUEL_LOW_TT_OFF_CHOICE (0u)
#define BINOCAN_ITF_ACTIVE_HI_LO_ITF_FUEL_LOW_TT_ON_CHOICE (1u)

/* Frame Names. */
#define BINOCAN_RDB_BOARD_VERSION_NAME "RDB_board_version"
#define BINOCAN_LDB_BOARD_VERSION_NAME "LDB_board_version"
#define BINOCAN_EXT_UDS_RESP_NAME "EXT_UDS_RESP"
#define BINOCAN_EXT_UDS_REQ_NAME "EXT_UDS_REQ"
#define BINOCAN_RDB_UDS_RESP_NAME "RDB_UDS_RESP"
#define BINOCAN_RDB_UDS_REQ_NAME "RDB_UDS_REQ"
#define BINOCAN_LDB_UDS_RESP_NAME "LDB_UDS_RESP"
#define BINOCAN_LDB_UDS_REQ_NAME "LDB_UDS_REQ"
#define BINOCAN_ITF_UDS_RESP_NAME "ITF_UDS_RESP"
#define BINOCAN_ITF_UDS_REQ_NAME "ITF_UDS_REQ"
#define BINOCAN_ITF_BOARD_VERSION_NAME "ITF_board_version"
#define BINOCAN_RDB_ST_NAME "RDB_ST"
#define BINOCAN_LDB_ST_NAME "LDB_ST"
#define BINOCAN_ITF_BOARD_ST_NAME "ITF_board_ST"
#define BINOCAN_ITF_ODOMETER_NAME "ITF_odometer"
#define BINOCAN_EXT_CHARGECOOLING_METRICS_NAME "EXT_chargecooling_metrics"
#define BINOCAN_ITF_ACTIVE_HI_LO_NAME "ITF_active_hi_lo"
#define BINOCAN_EXT_OIL_METRICS_NAME "EXT_oil_metrics"
#define BINOCAN_ITF_SLOW_METRICS_NAME "ITF_slow_metrics"
#define BINOCAN_ITF_FAST_METRICS_NAME "ITF_fast_metrics"

/* Signal Names. */
#define BINOCAN_RDB_BOARD_VERSION_RDB_VERSION_MUX_NAME "RDB_version_MUX"
#define BINOCAN_RDB_BOARD_VERSION_RDB_VERSION_DIRTY_NAME "RDB_version_dirty"
#define BINOCAN_RDB_BOARD_VERSION_RDB_VERSION_MAJOR_NAME "RDB_version_major"
#define BINOCAN_RDB_BOARD_VERSION_RDB_VERSION_COMMIT_NAME "RDB_version_commit"
#define BINOCAN_RDB_BOARD_VERSION_RDB_VERSION_MINOR_NAME "RDB_version_minor"
#define BINOCAN_RDB_BOARD_VERSION_RDB_VERSION_PATCH_NAME "RDB_version_patch"
#define BINOCAN_LDB_BOARD_VERSION_LDB_VERSION_MUX_NAME "LDB_version_MUX"
#define BINOCAN_LDB_BOARD_VERSION_LDB_VERSION_DIRTY_NAME "LDB_version_dirty"
#define BINOCAN_LDB_BOARD_VERSION_LDB_VERSION_COMMIT_NAME "LDB_version_commit"
#define BINOCAN_LDB_BOARD_VERSION_LDB_VERSION_MAJOR_NAME "LDB_version_major"
#define BINOCAN_LDB_BOARD_VERSION_LDB_VERSION_MINOR_NAME "LDB_version_minor"
#define BINOCAN_LDB_BOARD_VERSION_LDB_VERSION_PATCH_NAME "LDB_version_patch"
#define BINOCAN_EXT_UDS_RESP_EXT_UDS_RESP_NAME "EXT_uds_resp"
#define BINOCAN_EXT_UDS_REQ_EXT_UDS_REQ_NAME "EXT_uds_req"
#define BINOCAN_RDB_UDS_RESP_RDB_UDS_RESP_NAME "RDB_uds_resp"
#define BINOCAN_RDB_UDS_REQ_RDB_UDS_REQ_NAME "RDB_uds_req"
#define BINOCAN_LDB_UDS_RESP_LDB_UDS_RESP_NAME "LDB_uds_resp"
#define BINOCAN_LDB_UDS_REQ_LDB_UDS_REQ_NAME "LDB_uds_req"
#define BINOCAN_ITF_UDS_RESP_ITF_UDS_RESP_NAME "ITF_uds_resp"
#define BINOCAN_ITF_UDS_REQ_ITF_UDS_REQ_NAME "ITF_uds_req"
#define BINOCAN_ITF_BOARD_VERSION_ITF_VERSION_MUX_NAME "ITF_version_MUX"
#define BINOCAN_ITF_BOARD_VERSION_ITF_VERSION_DIRTY_NAME "ITF_version_dirty"
#define BINOCAN_ITF_BOARD_VERSION_ITF_VERSION_MAJOR_NAME "ITF_version_major"
#define BINOCAN_ITF_BOARD_VERSION_ITF_VERSION_COMMIT_NAME "ITF_version_commit"
#define BINOCAN_ITF_BOARD_VERSION_ITF_VERSION_MINOR_NAME "ITF_version_minor"
#define BINOCAN_ITF_BOARD_VERSION_ITF_VERSION_PATCH_NAME "ITF_version_patch"
#define BINOCAN_RDB_ST_RDB_SM_ST_NAME "RDB_SM_ST"
#define BINOCAN_LDB_ST_LDB_SM_ST_NAME "LDB_SM_ST"
#define BINOCAN_ITF_BOARD_ST_ITF_HI_R_SENSE_ST_NAME "ITF__Hi_R_sense_ST"
#define BINOCAN_ITF_BOARD_ST_ITF_EXPANDER_ST_NAME "ITF_expander_ST"
#define BINOCAN_ITF_BOARD_ST_ITF_ADC_ST_NAME "ITF_ADC_ST"
#define BINOCAN_ITF_BOARD_ST_ITF_5_V_AUX_ST_NAME "ITF_5V_AUX_ST"
#define BINOCAN_ITF_BOARD_ST_ITF_5_V_ST_NAME "ITF_5V_ST"
#define BINOCAN_ITF_BOARD_ST_ITF_LD_CHECK_ALIVE_ST_NAME "ITF_LD_check_alive_ST"
#define BINOCAN_ITF_BOARD_ST_ITF_RD_CHECK_ALIVE_ST_NAME "ITF_RD_check_alive_ST"
#define BINOCAN_ITF_BOARD_ST_ITF_SM_ST_NAME "ITF_SM_ST"
#define BINOCAN_ITF_BOARD_ST_ITF_MCU_TEMP_NAME "ITF_MCU_temp"
#define BINOCAN_ITF_ODOMETER_ITF_ODOMETER_KM_NAME "ITF_odometer_km"
#define BINOCAN_ITF_ODOMETER_ITF_ODO_REM_M_NAME "ITF_odo_rem_m"
#define BINOCAN_ITF_ODOMETER_ITF_TRIP_KM_NAME "ITF_trip_km"
#define BINOCAN_ITF_ODOMETER_ITF_TRIP_REM_M_NAME "ITF_trip_rem_m"
#define BINOCAN_EXT_CHARGECOOLING_METRICS_BITMASK_NAME "bitmask"
#define BINOCAN_EXT_CHARGECOOLING_METRICS_EXT_CHARGE_COOLANT_TEMP_IN_NAME "EXT_charge_coolant_temp_in"
#define BINOCAN_EXT_CHARGECOOLING_METRICS_EXT_CHARGE_COOLANT_TEMP_OUT_NAME "EXT_charge_coolant_temp_out"
#define BINOCAN_ITF_ACTIVE_HI_LO_ITF_IGNITION_AH_ST_NAME "ITF_ignition_AH_ST"
#define BINOCAN_ITF_ACTIVE_HI_LO_ITF_HI_BEAMS_AH_TT_NAME "ITF_hi_beams_AH_TT"
#define BINOCAN_ITF_ACTIVE_HI_LO_ITF_ALTERNATOR_AL_TT_NAME "ITF_alternator_AL_TT"
#define BINOCAN_ITF_ACTIVE_HI_LO_ITF_BRAKE_LOW_AL_TT_NAME "ITF_brake_low_AL_TT"
#define BINOCAN_ITF_ACTIVE_HI_LO_ITF_PARKING_BRAKE_AL_TT_NAME "ITF_parking_brake_AL_TT"
#define BINOCAN_ITF_ACTIVE_HI_LO_ITF_OIL_PRESSURE_AL_TT_NAME "ITF_oil_pressure_AL_TT"
#define BINOCAN_ITF_ACTIVE_HI_LO_ITF_AIRBAG_AL_TT_NAME "ITF_airbag_AL_TT"
#define BINOCAN_ITF_ACTIVE_HI_LO_ITF_CEL_AL_TT_NAME "ITF_CEL_AL_TT"
#define BINOCAN_ITF_ACTIVE_HI_LO_ITF_RIGHT_TURN_AH_TT_NAME "ITF_right_turn_AH_TT"
#define BINOCAN_ITF_ACTIVE_HI_LO_ITF_LEFT_TURN_AH_TT_NAME "ITF_left_turn_AH_TT"
#define BINOCAN_ITF_ACTIVE_HI_LO_ITF_ABS_AL_TT_NAME "ITF_abs_AL_TT"
#define BINOCAN_ITF_ACTIVE_HI_LO_ITF_DOOR_AL_TT_NAME "ITF_door_AL_TT"
#define BINOCAN_ITF_ACTIVE_HI_LO_ITF_COOLANT_LOW_AH_TT_NAME "ITF_coolant_low_AH_TT"
#define BINOCAN_ITF_ACTIVE_HI_LO_ITF_BUTTON_AL_NAME "ITF_button_AL"
#define BINOCAN_ITF_ACTIVE_HI_LO_ITF_ALARM_AH_NAME "ITF_alarm_AH"
#define BINOCAN_ITF_ACTIVE_HI_LO_ITF_BACKLIGHT_AH_NAME "ITF_backlight_AH"
#define BINOCAN_ITF_ACTIVE_HI_LO_ITF_OVER_TEMPERATURE_TT_NAME "ITF_over_temperature_TT"
#define BINOCAN_ITF_ACTIVE_HI_LO_ITF_FUEL_LOW_TT_NAME "ITF_fuel_low_TT"
#define BINOCAN_EXT_OIL_METRICS_BITMASK_NAME "bitmask"
#define BINOCAN_EXT_OIL_METRICS_EXT_OIL_PRESSURE_NAME "EXT_oil_pressure"
#define BINOCAN_EXT_OIL_METRICS_EXT_OIL_TEMPERATURE_NAME "EXT_oil_temperature"
#define BINOCAN_ITF_SLOW_METRICS_ITF_COOLANT_TEMP_NAME "ITF_coolant_temp"
#define BINOCAN_ITF_SLOW_METRICS_ITF_FUEL_LEVEL_PC_NAME "ITF_fuel_level_pc"
#define BINOCAN_ITF_SLOW_METRICS_ITF_LV_VOLTAGE_V_NAME "ITF_lv_voltage_v"
#define BINOCAN_ITF_FAST_METRICS_ITF_RPM_NAME "ITF_rpm"
#define BINOCAN_ITF_FAST_METRICS_ITF_SPEED_KPH_NAME "ITF_speed_kph"

/**
 * Signals in message RDB_board_version.
 *
 * Interface board software version information
 *
 * All signal values are as on the CAN bus.
 */
struct binocan_rdb_board_version_t {
    /**
     * Range: 0..3 (0..3 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t rdb_version_mux;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t rdb_version_dirty;

    /**
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t rdb_version_major;

    /**
     * Range: 0..72057594037927904 (0..7.20575940379279e+16 -)
     * Scale: 1
     * Offset: 0
     */
    uint64_t rdb_version_commit;

    /**
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t rdb_version_minor;

    /**
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t rdb_version_patch;
};

/**
 * Signals in message LDB_board_version.
 *
 * Interface board software version information
 *
 * All signal values are as on the CAN bus.
 */
struct binocan_ldb_board_version_t {
    /**
     * Range: 0..3 (0..3 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t ldb_version_mux;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t ldb_version_dirty;

    /**
     * Range: 0..72057594037927904 (0..7.20575940379279e+16 -)
     * Scale: 1
     * Offset: 0
     */
    uint64_t ldb_version_commit;

    /**
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t ldb_version_major;

    /**
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t ldb_version_minor;

    /**
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t ldb_version_patch;
};

/**
 * Signals in message EXT_UDS_RESP.
 *
 * External controller UDS response

 *
 * All signal values are as on the CAN bus.
 */
struct binocan_ext_uds_resp_t {
    /**
     * Range: 0..18446744073709600768 (0..1.84467440737096e+19 -)
     * Scale: 1
     * Offset: 0
     */
    uint64_t ext_uds_resp;
};

/**
 * Signals in message EXT_UDS_REQ.
 *
 * UDS requests to External controller

 *
 * All signal values are as on the CAN bus.
 */
struct binocan_ext_uds_req_t {
    /**
     * Range: 0..18446744073709600768 (0..1.84467440737096e+19 -)
     * Scale: 1
     * Offset: 0
     */
    uint64_t ext_uds_req;
};

/**
 * Signals in message RDB_UDS_RESP.
 *
 * UDS responses from the right display
 *
 * All signal values are as on the CAN bus.
 */
struct binocan_rdb_uds_resp_t {
    /**
     * Range: 0..18446744073709600768 (0..1.84467440737096e+19 -)
     * Scale: 1
     * Offset: 0
     */
    uint64_t rdb_uds_resp;
};

/**
 * Signals in message RDB_UDS_REQ.
 *
 * UDS requests to the right display
 *
 * All signal values are as on the CAN bus.
 */
struct binocan_rdb_uds_req_t {
    /**
     * Range: 0..18446744073709600768 (0..1.84467440737096e+19 -)
     * Scale: 1
     * Offset: 0
     */
    uint64_t rdb_uds_req;
};

/**
 * Signals in message LDB_UDS_RESP.
 *
 * UDS responses from the left display
 *
 * All signal values are as on the CAN bus.
 */
struct binocan_ldb_uds_resp_t {
    /**
     * Range: 0..18446744073709600768 (0..1.84467440737096e+19 -)
     * Scale: 1
     * Offset: 0
     */
    uint64_t ldb_uds_resp;
};

/**
 * Signals in message LDB_UDS_REQ.
 *
 * UDS requests to the left display
 *
 * All signal values are as on the CAN bus.
 */
struct binocan_ldb_uds_req_t {
    /**
     * Range: 0..18446744073709600768 (0..1.84467440737096e+19 -)
     * Scale: 1
     * Offset: 0
     */
    uint64_t ldb_uds_req;
};

/**
 * Signals in message ITF_UDS_RESP.
 *
 * UDS responses from the interface board
 *
 * All signal values are as on the CAN bus.
 */
struct binocan_itf_uds_resp_t {
    /**
     * Range: 0..18446744073709600768 (0..1.84467440737096e+19 -)
     * Scale: 1
     * Offset: 0
     */
    uint64_t itf_uds_resp;
};

/**
 * Signals in message ITF_UDS_REQ.
 *
 * UDS requests to the interface board
 *
 * All signal values are as on the CAN bus.
 */
struct binocan_itf_uds_req_t {
    /**
     * Range: 0..18446744073709600768 (0..1.84467440737096e+19 -)
     * Scale: 1
     * Offset: 0
     */
    uint64_t itf_uds_req;
};

/**
 * Signals in message ITF_board_version.
 *
 * Interface board software version information
 *
 * All signal values are as on the CAN bus.
 */
struct binocan_itf_board_version_t {
    /**
     * Range: 0..3 (0..3 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t itf_version_mux;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t itf_version_dirty;

    /**
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t itf_version_major;

    /**
     * Range: 0..72057594037927904 (0..7.20575940379279e+16 -)
     * Scale: 1
     * Offset: 0
     */
    uint64_t itf_version_commit;

    /**
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t itf_version_minor;

    /**
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t itf_version_patch;
};

/**
 * Signals in message RDB_ST.
 *
 * Right display board status

 *
 * All signal values are as on the CAN bus.
 */
struct binocan_rdb_st_t {
    /**
     * Range: 0..15 (0..15 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t rdb_sm_st;
};

/**
 * Signals in message LDB_ST.
 *
 * Left display board status

 *
 * All signal values are as on the CAN bus.
 */
struct binocan_ldb_st_t {
    /**
     * Range: 0..15 (0..15 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t ldb_sm_st;
};

/**
 * Signals in message ITF_board_ST.
 *
 * Interface board status

 *
 * All signal values are as on the CAN bus.
 */
struct binocan_itf_board_st_t {
    /**
     * Reports status of the interface board Hi R sense enable toggle.
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t itf_hi_r_sense_st;

    /**
     * Indicates if the IO expander on the interface board is in a valid (ON) or invalid (OFF) state.
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t itf_expander_st;

    /**
     * Indicates if the ADC on the interface board is in a valid (ON) or invalid (OFF) state.
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t itf_adc_st;

    /**
     * Status of the auxiliary 5V power supply. Linked to left display if present.
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t itf_5_v_aux_st;

    /**
     * Status of the main 5V power supply. Linked to right display if present, and main board CAN transceiver on older board revisions.
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t itf_5_v_st;

    /**
     * On if the left display is reporting a 3V3 signal.
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t itf_ld_check_alive_st;

    /**
     * On if the right display is reporting a 3V3 signal.
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t itf_rd_check_alive_st;

    /**
     * Interface board system status.
     *
     * Range: 0..7 (0..7 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t itf_sm_st;

    /**
     * Internal temperature of the MCU.
     *
     * Range: 0..127 (0..127 degC)
     * Scale: 1
     * Offset: 0
     */
    uint8_t itf_mcu_temp;
};

/**
 * Signals in message ITF_odometer.
 *
 * Odometer and trip information from interface board
 *
 * All signal values are as on the CAN bus.
 */
struct binocan_itf_odometer_t {
    /**
     * Odometer in km.
     *
     * Range: 0..1048575 (0..1048575 km)
     * Scale: 1
     * Offset: 0
     */
    uint32_t itf_odometer_km;

    /**
     * Odometer remaining hundreds of meter.
     *
     * Range: 0..15 (0..1500 m)
     * Scale: 100
     * Offset: 0
     */
    uint8_t itf_odo_rem_m;

    /**
     * Range: 0..999 (0..999 km)
     * Scale: 1
     * Offset: 0
     */
    uint16_t itf_trip_km;

    /**
     * Range: 0..15 (0..1500 m)
     * Scale: 100
     * Offset: 0
     */
    uint8_t itf_trip_rem_m;
};

/**
 * Signals in message EXT_chargecooling_metrics.
 *
 * Metrics related to chargecooling
 *
 * All signal values are as on the CAN bus.
 */
struct binocan_ext_chargecooling_metrics_t {
    /**
     * Bitmask used to highlight unavailable signals in a standard message
     *
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t bitmask;

    /**
     * Charge coolant temperature at intercooler inlet
     *
     * Range: 0..255 (0..255 degC)
     * Scale: 1
     * Offset: 0
     */
    uint8_t ext_charge_coolant_temp_in;

    /**
     * Charge coolant temperature out of the intake intercooler
     *
     * Range: 0..255 (0..255 degC)
     * Scale: 1
     * Offset: 0
     */
    uint8_t ext_charge_coolant_temp_out;
};

/**
 * Signals in message ITF_active_hi_lo.
 *
 * Medium priority cyclic and trigger telltale message
 *
 * All signal values are as on the CAN bus.
 */
struct binocan_itf_active_hi_lo_t {
    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t itf_ignition_ah_st;

    /**
     * High beams telltale
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t itf_hi_beams_ah_tt;

    /**
     * Battery or alternator telltale
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t itf_alternator_al_tt;

    /**
     * Low brake fluid telltale
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t itf_brake_low_al_tt;

    /**
     * Parking brake telltale
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t itf_parking_brake_al_tt;

    /**
     * Low oil pressure telltale
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t itf_oil_pressure_al_tt;

    /**
     * Airbag telltale
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t itf_airbag_al_tt;

    /**
     * Check Engine Light telltale
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t itf_cel_al_tt;

    /**
     * Turn indicators telltale
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t itf_right_turn_ah_tt;

    /**
     * Turn indicators telltale
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t itf_left_turn_ah_tt;

    /**
     * ABS telltale
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t itf_abs_al_tt;

    /**
     * Door telltale status
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t itf_door_al_tt;

    /**
     * Low coolant level telltale
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t itf_coolant_low_ah_tt;

    /**
     * Button status
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t itf_button_al;

    /**
     * Unknown active high. Could be alarm or revlight
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t itf_alarm_ah;

    /**
     * LCD backlight input, might be related to headlights in low beam or position.
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t itf_backlight_ah;

    /**
     * Coolant overtemperature telltale
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t itf_over_temperature_tt;

    /**
     * Low fuel level telltale
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t itf_fuel_low_tt;
};

/**
 * Signals in message EXT_oil_metrics.
 *
 * Message for extra measurements related to oil metrics
 *
 * All signal values are as on the CAN bus.
 */
struct binocan_ext_oil_metrics_t {
    /**
     * Bitmask used to highlight unavailable signals in a standard message
     *
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t bitmask;

    /**
     * Optional oil pressure reading
     *
     * Range: 0..255 (0..25.5 bar)
     * Scale: 0.1
     * Offset: 0
     */
    uint8_t ext_oil_pressure;

    /**
     * Optional oil temperature reading
     *
     * Range: 0..255 (0..255 degC)
     * Scale: 1
     * Offset: 0
     */
    uint8_t ext_oil_temperature;
};

/**
 * Signals in message ITF_slow_metrics.
 *
 * Slow cyclic message with numerical readings
 *
 * All signal values are as on the CAN bus.
 */
struct binocan_itf_slow_metrics_t {
    /**
     * Indicated coolant temperature
     *
     * Range: 0..200 (70..150 degC)
     * Scale: 0.4
     * Offset: 70
     */
    uint8_t itf_coolant_temp;

    /**
     * Relative fuel tank level
     *
     * Range: 0..202 (0..101 pc)
     * Scale: 0.5
     * Offset: 0
     */
    uint8_t itf_fuel_level_pc;

    /**
     * 12V measured after protection circuitry
     *
     * Range: 0..200 (0..20 V)
     * Scale: 0.1
     * Offset: 0
     */
    uint8_t itf_lv_voltage_v;
};

/**
 * Signals in message ITF_fast_metrics.
 *
 * Fast cyclic message for base vehicle metrics and telltale triggers
 *
 * All signal values are as on the CAN bus.
 */
struct binocan_itf_fast_metrics_t {
    /**
     * Engine rotations in RPM
     *
     * Range: 0..65535 (0..9174.9 -)
     * Scale: 0.14
     * Offset: 0
     */
    uint16_t itf_rpm;

    /**
     * Vehicle speed in km/h
     *
     * Range: 0..10000 (0..400 kph)
     * Scale: 0.04
     * Offset: 0
     */
    uint16_t itf_speed_kph;
};

/**
 * Pack message RDB_board_version.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int binocan_rdb_board_version_pack(
    uint8_t *dst_p,
    const struct binocan_rdb_board_version_t *src_p,
    size_t size);

/**
 * Unpack message RDB_board_version.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int binocan_rdb_board_version_unpack(
    struct binocan_rdb_board_version_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from RDB_board_version.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int binocan_rdb_board_version_init(struct binocan_rdb_board_version_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_rdb_board_version_rdb_version_mux_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_rdb_board_version_rdb_version_mux_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_rdb_board_version_rdb_version_mux_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_rdb_board_version_rdb_version_dirty_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_rdb_board_version_rdb_version_dirty_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_rdb_board_version_rdb_version_dirty_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_rdb_board_version_rdb_version_major_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_rdb_board_version_rdb_version_major_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_rdb_board_version_rdb_version_major_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint64_t binocan_rdb_board_version_rdb_version_commit_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_rdb_board_version_rdb_version_commit_decode(uint64_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_rdb_board_version_rdb_version_commit_is_in_range(uint64_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_rdb_board_version_rdb_version_minor_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_rdb_board_version_rdb_version_minor_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_rdb_board_version_rdb_version_minor_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_rdb_board_version_rdb_version_patch_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_rdb_board_version_rdb_version_patch_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_rdb_board_version_rdb_version_patch_is_in_range(uint8_t value);

/**
 * Pack message LDB_board_version.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int binocan_ldb_board_version_pack(
    uint8_t *dst_p,
    const struct binocan_ldb_board_version_t *src_p,
    size_t size);

/**
 * Unpack message LDB_board_version.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int binocan_ldb_board_version_unpack(
    struct binocan_ldb_board_version_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from LDB_board_version.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int binocan_ldb_board_version_init(struct binocan_ldb_board_version_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_ldb_board_version_ldb_version_mux_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_ldb_board_version_ldb_version_mux_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_ldb_board_version_ldb_version_mux_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_ldb_board_version_ldb_version_dirty_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_ldb_board_version_ldb_version_dirty_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_ldb_board_version_ldb_version_dirty_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint64_t binocan_ldb_board_version_ldb_version_commit_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_ldb_board_version_ldb_version_commit_decode(uint64_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_ldb_board_version_ldb_version_commit_is_in_range(uint64_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_ldb_board_version_ldb_version_major_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_ldb_board_version_ldb_version_major_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_ldb_board_version_ldb_version_major_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_ldb_board_version_ldb_version_minor_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_ldb_board_version_ldb_version_minor_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_ldb_board_version_ldb_version_minor_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_ldb_board_version_ldb_version_patch_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_ldb_board_version_ldb_version_patch_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_ldb_board_version_ldb_version_patch_is_in_range(uint8_t value);

/**
 * Pack message EXT_UDS_RESP.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int binocan_ext_uds_resp_pack(
    uint8_t *dst_p,
    const struct binocan_ext_uds_resp_t *src_p,
    size_t size);

/**
 * Unpack message EXT_UDS_RESP.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int binocan_ext_uds_resp_unpack(
    struct binocan_ext_uds_resp_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from EXT_UDS_RESP.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int binocan_ext_uds_resp_init(struct binocan_ext_uds_resp_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint64_t binocan_ext_uds_resp_ext_uds_resp_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_ext_uds_resp_ext_uds_resp_decode(uint64_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_ext_uds_resp_ext_uds_resp_is_in_range(uint64_t value);

/**
 * Pack message EXT_UDS_REQ.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int binocan_ext_uds_req_pack(
    uint8_t *dst_p,
    const struct binocan_ext_uds_req_t *src_p,
    size_t size);

/**
 * Unpack message EXT_UDS_REQ.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int binocan_ext_uds_req_unpack(
    struct binocan_ext_uds_req_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from EXT_UDS_REQ.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int binocan_ext_uds_req_init(struct binocan_ext_uds_req_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint64_t binocan_ext_uds_req_ext_uds_req_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_ext_uds_req_ext_uds_req_decode(uint64_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_ext_uds_req_ext_uds_req_is_in_range(uint64_t value);

/**
 * Pack message RDB_UDS_RESP.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int binocan_rdb_uds_resp_pack(
    uint8_t *dst_p,
    const struct binocan_rdb_uds_resp_t *src_p,
    size_t size);

/**
 * Unpack message RDB_UDS_RESP.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int binocan_rdb_uds_resp_unpack(
    struct binocan_rdb_uds_resp_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from RDB_UDS_RESP.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int binocan_rdb_uds_resp_init(struct binocan_rdb_uds_resp_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint64_t binocan_rdb_uds_resp_rdb_uds_resp_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_rdb_uds_resp_rdb_uds_resp_decode(uint64_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_rdb_uds_resp_rdb_uds_resp_is_in_range(uint64_t value);

/**
 * Pack message RDB_UDS_REQ.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int binocan_rdb_uds_req_pack(
    uint8_t *dst_p,
    const struct binocan_rdb_uds_req_t *src_p,
    size_t size);

/**
 * Unpack message RDB_UDS_REQ.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int binocan_rdb_uds_req_unpack(
    struct binocan_rdb_uds_req_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from RDB_UDS_REQ.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int binocan_rdb_uds_req_init(struct binocan_rdb_uds_req_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint64_t binocan_rdb_uds_req_rdb_uds_req_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_rdb_uds_req_rdb_uds_req_decode(uint64_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_rdb_uds_req_rdb_uds_req_is_in_range(uint64_t value);

/**
 * Pack message LDB_UDS_RESP.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int binocan_ldb_uds_resp_pack(
    uint8_t *dst_p,
    const struct binocan_ldb_uds_resp_t *src_p,
    size_t size);

/**
 * Unpack message LDB_UDS_RESP.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int binocan_ldb_uds_resp_unpack(
    struct binocan_ldb_uds_resp_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from LDB_UDS_RESP.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int binocan_ldb_uds_resp_init(struct binocan_ldb_uds_resp_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint64_t binocan_ldb_uds_resp_ldb_uds_resp_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_ldb_uds_resp_ldb_uds_resp_decode(uint64_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_ldb_uds_resp_ldb_uds_resp_is_in_range(uint64_t value);

/**
 * Pack message LDB_UDS_REQ.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int binocan_ldb_uds_req_pack(
    uint8_t *dst_p,
    const struct binocan_ldb_uds_req_t *src_p,
    size_t size);

/**
 * Unpack message LDB_UDS_REQ.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int binocan_ldb_uds_req_unpack(
    struct binocan_ldb_uds_req_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from LDB_UDS_REQ.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int binocan_ldb_uds_req_init(struct binocan_ldb_uds_req_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint64_t binocan_ldb_uds_req_ldb_uds_req_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_ldb_uds_req_ldb_uds_req_decode(uint64_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_ldb_uds_req_ldb_uds_req_is_in_range(uint64_t value);

/**
 * Pack message ITF_UDS_RESP.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int binocan_itf_uds_resp_pack(
    uint8_t *dst_p,
    const struct binocan_itf_uds_resp_t *src_p,
    size_t size);

/**
 * Unpack message ITF_UDS_RESP.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int binocan_itf_uds_resp_unpack(
    struct binocan_itf_uds_resp_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from ITF_UDS_RESP.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int binocan_itf_uds_resp_init(struct binocan_itf_uds_resp_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint64_t binocan_itf_uds_resp_itf_uds_resp_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_itf_uds_resp_itf_uds_resp_decode(uint64_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_itf_uds_resp_itf_uds_resp_is_in_range(uint64_t value);

/**
 * Pack message ITF_UDS_REQ.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int binocan_itf_uds_req_pack(
    uint8_t *dst_p,
    const struct binocan_itf_uds_req_t *src_p,
    size_t size);

/**
 * Unpack message ITF_UDS_REQ.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int binocan_itf_uds_req_unpack(
    struct binocan_itf_uds_req_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from ITF_UDS_REQ.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int binocan_itf_uds_req_init(struct binocan_itf_uds_req_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint64_t binocan_itf_uds_req_itf_uds_req_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_itf_uds_req_itf_uds_req_decode(uint64_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_itf_uds_req_itf_uds_req_is_in_range(uint64_t value);

/**
 * Pack message ITF_board_version.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int binocan_itf_board_version_pack(
    uint8_t *dst_p,
    const struct binocan_itf_board_version_t *src_p,
    size_t size);

/**
 * Unpack message ITF_board_version.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int binocan_itf_board_version_unpack(
    struct binocan_itf_board_version_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from ITF_board_version.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int binocan_itf_board_version_init(struct binocan_itf_board_version_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_itf_board_version_itf_version_mux_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_itf_board_version_itf_version_mux_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_itf_board_version_itf_version_mux_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_itf_board_version_itf_version_dirty_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_itf_board_version_itf_version_dirty_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_itf_board_version_itf_version_dirty_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_itf_board_version_itf_version_major_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_itf_board_version_itf_version_major_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_itf_board_version_itf_version_major_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint64_t binocan_itf_board_version_itf_version_commit_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_itf_board_version_itf_version_commit_decode(uint64_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_itf_board_version_itf_version_commit_is_in_range(uint64_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_itf_board_version_itf_version_minor_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_itf_board_version_itf_version_minor_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_itf_board_version_itf_version_minor_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_itf_board_version_itf_version_patch_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_itf_board_version_itf_version_patch_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_itf_board_version_itf_version_patch_is_in_range(uint8_t value);

/**
 * Pack message RDB_ST.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int binocan_rdb_st_pack(
    uint8_t *dst_p,
    const struct binocan_rdb_st_t *src_p,
    size_t size);

/**
 * Unpack message RDB_ST.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int binocan_rdb_st_unpack(
    struct binocan_rdb_st_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from RDB_ST.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int binocan_rdb_st_init(struct binocan_rdb_st_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_rdb_st_rdb_sm_st_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_rdb_st_rdb_sm_st_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_rdb_st_rdb_sm_st_is_in_range(uint8_t value);

/**
 * Pack message LDB_ST.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int binocan_ldb_st_pack(
    uint8_t *dst_p,
    const struct binocan_ldb_st_t *src_p,
    size_t size);

/**
 * Unpack message LDB_ST.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int binocan_ldb_st_unpack(
    struct binocan_ldb_st_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from LDB_ST.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int binocan_ldb_st_init(struct binocan_ldb_st_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_ldb_st_ldb_sm_st_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_ldb_st_ldb_sm_st_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_ldb_st_ldb_sm_st_is_in_range(uint8_t value);

/**
 * Pack message ITF_board_ST.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int binocan_itf_board_st_pack(
    uint8_t *dst_p,
    const struct binocan_itf_board_st_t *src_p,
    size_t size);

/**
 * Unpack message ITF_board_ST.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int binocan_itf_board_st_unpack(
    struct binocan_itf_board_st_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from ITF_board_ST.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int binocan_itf_board_st_init(struct binocan_itf_board_st_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_itf_board_st_itf_hi_r_sense_st_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_itf_board_st_itf_hi_r_sense_st_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_itf_board_st_itf_hi_r_sense_st_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_itf_board_st_itf_expander_st_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_itf_board_st_itf_expander_st_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_itf_board_st_itf_expander_st_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_itf_board_st_itf_adc_st_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_itf_board_st_itf_adc_st_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_itf_board_st_itf_adc_st_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_itf_board_st_itf_5_v_aux_st_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_itf_board_st_itf_5_v_aux_st_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_itf_board_st_itf_5_v_aux_st_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_itf_board_st_itf_5_v_st_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_itf_board_st_itf_5_v_st_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_itf_board_st_itf_5_v_st_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_itf_board_st_itf_ld_check_alive_st_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_itf_board_st_itf_ld_check_alive_st_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_itf_board_st_itf_ld_check_alive_st_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_itf_board_st_itf_rd_check_alive_st_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_itf_board_st_itf_rd_check_alive_st_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_itf_board_st_itf_rd_check_alive_st_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_itf_board_st_itf_sm_st_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_itf_board_st_itf_sm_st_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_itf_board_st_itf_sm_st_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_itf_board_st_itf_mcu_temp_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_itf_board_st_itf_mcu_temp_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_itf_board_st_itf_mcu_temp_is_in_range(uint8_t value);

/**
 * Pack message ITF_odometer.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int binocan_itf_odometer_pack(
    uint8_t *dst_p,
    const struct binocan_itf_odometer_t *src_p,
    size_t size);

/**
 * Unpack message ITF_odometer.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int binocan_itf_odometer_unpack(
    struct binocan_itf_odometer_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from ITF_odometer.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int binocan_itf_odometer_init(struct binocan_itf_odometer_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint32_t binocan_itf_odometer_itf_odometer_km_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_itf_odometer_itf_odometer_km_decode(uint32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_itf_odometer_itf_odometer_km_is_in_range(uint32_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_itf_odometer_itf_odo_rem_m_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_itf_odometer_itf_odo_rem_m_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_itf_odometer_itf_odo_rem_m_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t binocan_itf_odometer_itf_trip_km_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_itf_odometer_itf_trip_km_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_itf_odometer_itf_trip_km_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_itf_odometer_itf_trip_rem_m_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_itf_odometer_itf_trip_rem_m_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_itf_odometer_itf_trip_rem_m_is_in_range(uint8_t value);

/**
 * Pack message EXT_chargecooling_metrics.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int binocan_ext_chargecooling_metrics_pack(
    uint8_t *dst_p,
    const struct binocan_ext_chargecooling_metrics_t *src_p,
    size_t size);

/**
 * Unpack message EXT_chargecooling_metrics.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int binocan_ext_chargecooling_metrics_unpack(
    struct binocan_ext_chargecooling_metrics_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from EXT_chargecooling_metrics.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int binocan_ext_chargecooling_metrics_init(struct binocan_ext_chargecooling_metrics_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_ext_chargecooling_metrics_bitmask_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_ext_chargecooling_metrics_bitmask_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_ext_chargecooling_metrics_bitmask_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_ext_chargecooling_metrics_ext_charge_coolant_temp_in_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_ext_chargecooling_metrics_ext_charge_coolant_temp_in_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_ext_chargecooling_metrics_ext_charge_coolant_temp_in_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_ext_chargecooling_metrics_ext_charge_coolant_temp_out_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_ext_chargecooling_metrics_ext_charge_coolant_temp_out_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_ext_chargecooling_metrics_ext_charge_coolant_temp_out_is_in_range(uint8_t value);

/**
 * Pack message ITF_active_hi_lo.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int binocan_itf_active_hi_lo_pack(
    uint8_t *dst_p,
    const struct binocan_itf_active_hi_lo_t *src_p,
    size_t size);

/**
 * Unpack message ITF_active_hi_lo.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int binocan_itf_active_hi_lo_unpack(
    struct binocan_itf_active_hi_lo_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from ITF_active_hi_lo.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int binocan_itf_active_hi_lo_init(struct binocan_itf_active_hi_lo_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_itf_active_hi_lo_itf_ignition_ah_st_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_itf_active_hi_lo_itf_ignition_ah_st_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_itf_active_hi_lo_itf_ignition_ah_st_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_itf_active_hi_lo_itf_hi_beams_ah_tt_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_itf_active_hi_lo_itf_hi_beams_ah_tt_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_itf_active_hi_lo_itf_hi_beams_ah_tt_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_itf_active_hi_lo_itf_alternator_al_tt_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_itf_active_hi_lo_itf_alternator_al_tt_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_itf_active_hi_lo_itf_alternator_al_tt_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_itf_active_hi_lo_itf_brake_low_al_tt_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_itf_active_hi_lo_itf_brake_low_al_tt_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_itf_active_hi_lo_itf_brake_low_al_tt_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_itf_active_hi_lo_itf_parking_brake_al_tt_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_itf_active_hi_lo_itf_parking_brake_al_tt_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_itf_active_hi_lo_itf_parking_brake_al_tt_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_itf_active_hi_lo_itf_oil_pressure_al_tt_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_itf_active_hi_lo_itf_oil_pressure_al_tt_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_itf_active_hi_lo_itf_oil_pressure_al_tt_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_itf_active_hi_lo_itf_airbag_al_tt_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_itf_active_hi_lo_itf_airbag_al_tt_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_itf_active_hi_lo_itf_airbag_al_tt_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_itf_active_hi_lo_itf_cel_al_tt_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_itf_active_hi_lo_itf_cel_al_tt_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_itf_active_hi_lo_itf_cel_al_tt_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_itf_active_hi_lo_itf_right_turn_ah_tt_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_itf_active_hi_lo_itf_right_turn_ah_tt_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_itf_active_hi_lo_itf_right_turn_ah_tt_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_itf_active_hi_lo_itf_left_turn_ah_tt_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_itf_active_hi_lo_itf_left_turn_ah_tt_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_itf_active_hi_lo_itf_left_turn_ah_tt_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_itf_active_hi_lo_itf_abs_al_tt_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_itf_active_hi_lo_itf_abs_al_tt_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_itf_active_hi_lo_itf_abs_al_tt_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_itf_active_hi_lo_itf_door_al_tt_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_itf_active_hi_lo_itf_door_al_tt_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_itf_active_hi_lo_itf_door_al_tt_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_itf_active_hi_lo_itf_coolant_low_ah_tt_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_itf_active_hi_lo_itf_coolant_low_ah_tt_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_itf_active_hi_lo_itf_coolant_low_ah_tt_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_itf_active_hi_lo_itf_button_al_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_itf_active_hi_lo_itf_button_al_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_itf_active_hi_lo_itf_button_al_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_itf_active_hi_lo_itf_alarm_ah_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_itf_active_hi_lo_itf_alarm_ah_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_itf_active_hi_lo_itf_alarm_ah_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_itf_active_hi_lo_itf_backlight_ah_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_itf_active_hi_lo_itf_backlight_ah_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_itf_active_hi_lo_itf_backlight_ah_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_itf_active_hi_lo_itf_over_temperature_tt_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_itf_active_hi_lo_itf_over_temperature_tt_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_itf_active_hi_lo_itf_over_temperature_tt_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_itf_active_hi_lo_itf_fuel_low_tt_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_itf_active_hi_lo_itf_fuel_low_tt_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_itf_active_hi_lo_itf_fuel_low_tt_is_in_range(uint8_t value);

/**
 * Pack message EXT_oil_metrics.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int binocan_ext_oil_metrics_pack(
    uint8_t *dst_p,
    const struct binocan_ext_oil_metrics_t *src_p,
    size_t size);

/**
 * Unpack message EXT_oil_metrics.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int binocan_ext_oil_metrics_unpack(
    struct binocan_ext_oil_metrics_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from EXT_oil_metrics.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int binocan_ext_oil_metrics_init(struct binocan_ext_oil_metrics_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_ext_oil_metrics_bitmask_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_ext_oil_metrics_bitmask_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_ext_oil_metrics_bitmask_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_ext_oil_metrics_ext_oil_pressure_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_ext_oil_metrics_ext_oil_pressure_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_ext_oil_metrics_ext_oil_pressure_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_ext_oil_metrics_ext_oil_temperature_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_ext_oil_metrics_ext_oil_temperature_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_ext_oil_metrics_ext_oil_temperature_is_in_range(uint8_t value);

/**
 * Pack message ITF_slow_metrics.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int binocan_itf_slow_metrics_pack(
    uint8_t *dst_p,
    const struct binocan_itf_slow_metrics_t *src_p,
    size_t size);

/**
 * Unpack message ITF_slow_metrics.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int binocan_itf_slow_metrics_unpack(
    struct binocan_itf_slow_metrics_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from ITF_slow_metrics.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int binocan_itf_slow_metrics_init(struct binocan_itf_slow_metrics_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_itf_slow_metrics_itf_coolant_temp_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_itf_slow_metrics_itf_coolant_temp_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_itf_slow_metrics_itf_coolant_temp_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_itf_slow_metrics_itf_fuel_level_pc_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_itf_slow_metrics_itf_fuel_level_pc_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_itf_slow_metrics_itf_fuel_level_pc_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t binocan_itf_slow_metrics_itf_lv_voltage_v_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_itf_slow_metrics_itf_lv_voltage_v_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_itf_slow_metrics_itf_lv_voltage_v_is_in_range(uint8_t value);

/**
 * Pack message ITF_fast_metrics.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int binocan_itf_fast_metrics_pack(
    uint8_t *dst_p,
    const struct binocan_itf_fast_metrics_t *src_p,
    size_t size);

/**
 * Unpack message ITF_fast_metrics.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int binocan_itf_fast_metrics_unpack(
    struct binocan_itf_fast_metrics_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from ITF_fast_metrics.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int binocan_itf_fast_metrics_init(struct binocan_itf_fast_metrics_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t binocan_itf_fast_metrics_itf_rpm_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_itf_fast_metrics_itf_rpm_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_itf_fast_metrics_itf_rpm_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t binocan_itf_fast_metrics_itf_speed_kph_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double binocan_itf_fast_metrics_itf_speed_kph_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool binocan_itf_fast_metrics_itf_speed_kph_is_in_range(uint16_t value);


#ifdef __cplusplus
}
#endif

#endif
